-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_optimized is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_optimized is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_optimized_conv2d_optimized,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a25t-cpg238-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.241000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=6666,HLS_SYN_LUT=5612,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_read_reg_304 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_read_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal smax_fu_232_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax_reg_369 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax3_fu_240_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal smax3_reg_374 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln196_fu_208_p2 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln196_reg_379 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln196_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln196_reg_411 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln197_fu_298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln197_reg_416 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_idle : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_ready : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_ce0 : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out1_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out2_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out3_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out4_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out5_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out6_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out7_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out8_ap_vld : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_idle : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_ready : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal out_stream_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_stream_TUSER_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TID_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal out_stream_TDEST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln196_fu_208_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal mul_ln196_fu_208_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_36_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_35_fu_216_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal icmp_ln118_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_212_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal mul_ln196_fu_208_p00 : STD_LOGIC_VECTOR (61 downto 0);
    signal mul_ln196_fu_208_p10 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_optimized_conv2d_optimized_Pipeline_LOAD_KERNEL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : OUT STD_LOGIC;
        kernel_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_optimized_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln196 : IN STD_LOGIC_VECTOR (61 downto 0);
        add_ln196 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        p_reload48 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload47 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload46 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload45 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload44 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload43 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload42 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload41 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_ln197 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_optimized_mul_31ns_31ns_62_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        dout : OUT STD_LOGIC_VECTOR (61 downto 0) );
    end component;


    component conv2d_optimized_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : IN STD_LOGIC;
        kernel_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_optimized_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144 : component conv2d_optimized_conv2d_optimized_Pipeline_LOAD_KERNEL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start,
        ap_done => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done,
        ap_idle => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_idle,
        ap_ready => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_ready,
        kernel_address0 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_address0,
        kernel_ce0 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_ce0,
        kernel_q0 => kernel_q0,
        p_out => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out,
        p_out_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out_ap_vld,
        p_out1 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out1,
        p_out1_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out1_ap_vld,
        p_out2 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out2,
        p_out2_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out2_ap_vld,
        p_out3 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out3,
        p_out3_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out3_ap_vld,
        p_out4 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out4,
        p_out4_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out4_ap_vld,
        p_out5 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out5,
        p_out5_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out5_ap_vld,
        p_out6 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out6,
        p_out6_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out6_ap_vld,
        p_out7 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out7,
        p_out7_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out7_ap_vld,
        p_out8 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out8,
        p_out8_ap_vld => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out8_ap_vld);

    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159 : component conv2d_optimized_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start,
        ap_done => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done,
        ap_idle => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_idle,
        ap_ready => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TREADY,
        cols => cols_read_reg_304,
        mul_ln196 => mul_ln196_reg_379,
        add_ln196 => add_ln196_reg_411,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        p_reload48 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out8,
        p_reload47 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out7,
        p_reload46 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out6,
        p_reload45 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out5,
        p_reload44 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out4,
        p_reload43 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out3,
        p_reload42 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out2,
        p_reload41 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out1,
        p_reload => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_p_out,
        add_ln197 => add_ln197_reg_416,
        out_stream_TDATA => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        out_stream_TKEEP => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TSTRB,
        out_stream_TUSER => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TUSER,
        out_stream_TLAST => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TLAST,
        out_stream_TID => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TID,
        out_stream_TDEST => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDEST);

    control_s_axi_U : component conv2d_optimized_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rows => rows,
        cols => cols,
        kernel_address0 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_address0,
        kernel_ce0 => grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_kernel_ce0,
        kernel_q0 => kernel_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_31ns_31ns_62_1_1_U62 : component conv2d_optimized_mul_31ns_31ns_62_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 31,
        dout_WIDTH => 62)
    port map (
        din0 => mul_ln196_fu_208_p0,
        din1 => mul_ln196_fu_208_p1,
        dout => mul_ln196_fu_208_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TKEEP_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TSTRB_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TUSER_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TID_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_optimized_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDEST_int_regslice,
        vld_in => grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln196_reg_411 <= add_ln196_fu_292_p2;
                add_ln197_reg_416 <= add_ln197_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cols_read_reg_304 <= cols;
                rows_read_reg_310 <= rows;
                smax3_reg_374 <= smax3_fu_240_p3;
                smax_reg_369 <= smax_fu_232_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                mul_ln196_reg_379 <= mul_ln196_fu_208_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then
                out_stream_TDATA_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDATA;
                out_stream_TDEST_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDEST;
                out_stream_TID_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TID;
                out_stream_TKEEP_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TKEEP;
                out_stream_TLAST_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TLAST;
                out_stream_TSTRB_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TSTRB;
                out_stream_TUSER_reg <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TUSER;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln196_fu_292_p2 <= std_logic_vector(unsigned(rows_read_reg_310) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln197_fu_298_p2 <= std_logic_vector(unsigned(cols_read_reg_304) + unsigned(ap_const_lv32_FFFFFFFF));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done)
    begin
        if ((grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done)
    begin
        if ((grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    empty_35_fu_216_p1 <= rows(31 - 1 downto 0);
    empty_36_fu_226_p2 <= "1" when (signed(rows) > signed(ap_const_lv32_0)) else "0";
    empty_fu_212_p1 <= cols(31 - 1 downto 0);
    grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start <= grp_conv2d_optimized_Pipeline_LOAD_KERNEL_fu_144_ap_start_reg;
    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_ap_start_reg;
    grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state4);
    icmp_ln118_fu_220_p2 <= "1" when (signed(cols) > signed(ap_const_lv32_0)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_in_stream_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln196_fu_208_p0 <= mul_ln196_fu_208_p00(31 - 1 downto 0);
    mul_ln196_fu_208_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax_reg_369),62));
    mul_ln196_fu_208_p1 <= mul_ln196_fu_208_p10(31 - 1 downto 0);
    mul_ln196_fu_208_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(smax3_reg_374),62));

    out_stream_TDATA_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDATA, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, ap_CS_fsm_state4, out_stream_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TDATA_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDATA;
        else 
            out_stream_TDATA_int_regslice <= out_stream_TDATA_reg;
        end if; 
    end process;


    out_stream_TDEST_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDEST, ap_CS_fsm_state4, out_stream_TDEST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TDEST_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TDEST;
        else 
            out_stream_TDEST_int_regslice <= out_stream_TDEST_reg;
        end if; 
    end process;


    out_stream_TID_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TID, ap_CS_fsm_state4, out_stream_TID_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TID_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TID;
        else 
            out_stream_TID_int_regslice <= out_stream_TID_reg;
        end if; 
    end process;


    out_stream_TKEEP_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TKEEP, ap_CS_fsm_state4, out_stream_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TKEEP_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TKEEP;
        else 
            out_stream_TKEEP_int_regslice <= out_stream_TKEEP_reg;
        end if; 
    end process;


    out_stream_TLAST_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TLAST, ap_CS_fsm_state4, out_stream_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TLAST_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TLAST;
        else 
            out_stream_TLAST_int_regslice <= out_stream_TLAST_reg;
        end if; 
    end process;


    out_stream_TSTRB_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TSTRB, ap_CS_fsm_state4, out_stream_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TSTRB_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TSTRB;
        else 
            out_stream_TSTRB_int_regslice <= out_stream_TSTRB_reg;
        end if; 
    end process;


    out_stream_TUSER_int_regslice_assign_proc : process(grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID, grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TUSER, ap_CS_fsm_state4, out_stream_TUSER_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID = ap_const_logic_1))) then 
            out_stream_TUSER_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TUSER;
        else 
            out_stream_TUSER_int_regslice <= out_stream_TUSER_reg;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_optimized_Pipeline_ROW_LOOP_COL_LOOP_fu_159_out_stream_TVALID;
    smax3_fu_240_p3 <= 
        empty_fu_212_p1 when (icmp_ln118_fu_220_p2(0) = '1') else 
        ap_const_lv31_0;
    smax_fu_232_p3 <= 
        empty_35_fu_216_p1 when (empty_36_fu_226_p2(0) = '1') else 
        ap_const_lv31_0;
end behav;
