// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2d_stream_conv2d_stream_Pipeline_localKernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kernel_address0,
        kernel_ce0,
        kernel_q0,
        local_kernel_24_01136_out,
        local_kernel_24_01136_out_ap_vld,
        local_kernel_23_01135_out,
        local_kernel_23_01135_out_ap_vld,
        local_kernel_22_01134_out,
        local_kernel_22_01134_out_ap_vld,
        local_kernel_21_01133_out,
        local_kernel_21_01133_out_ap_vld,
        local_kernel_20_01132_out,
        local_kernel_20_01132_out_ap_vld,
        local_kernel_19_01131_out,
        local_kernel_19_01131_out_ap_vld,
        local_kernel_18_01130_out,
        local_kernel_18_01130_out_ap_vld,
        local_kernel_17_01129_out,
        local_kernel_17_01129_out_ap_vld,
        local_kernel_16_01128_out,
        local_kernel_16_01128_out_ap_vld,
        local_kernel_15_01127_out,
        local_kernel_15_01127_out_ap_vld,
        local_kernel_14_01126_out,
        local_kernel_14_01126_out_ap_vld,
        local_kernel_13_01125_out,
        local_kernel_13_01125_out_ap_vld,
        local_kernel_12_01124_out,
        local_kernel_12_01124_out_ap_vld,
        local_kernel_11_01123_out,
        local_kernel_11_01123_out_ap_vld,
        local_kernel_10_01122_out,
        local_kernel_10_01122_out_ap_vld,
        local_kernel_9_01121_out,
        local_kernel_9_01121_out_ap_vld,
        local_kernel_8_01120_out,
        local_kernel_8_01120_out_ap_vld,
        local_kernel_7_01119_out,
        local_kernel_7_01119_out_ap_vld,
        local_kernel_6_01118_out,
        local_kernel_6_01118_out_ap_vld,
        local_kernel_5_01117_out,
        local_kernel_5_01117_out_ap_vld,
        local_kernel_4_01116_out,
        local_kernel_4_01116_out_ap_vld,
        local_kernel_3_01115_out,
        local_kernel_3_01115_out_ap_vld,
        local_kernel_2_01114_out,
        local_kernel_2_01114_out_ap_vld,
        local_kernel_1_01113_out,
        local_kernel_1_01113_out_ap_vld,
        local_kernel_0_01112_out,
        local_kernel_0_01112_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] kernel_address0;
output   kernel_ce0;
input  [31:0] kernel_q0;
output  [31:0] local_kernel_24_01136_out;
output   local_kernel_24_01136_out_ap_vld;
output  [31:0] local_kernel_23_01135_out;
output   local_kernel_23_01135_out_ap_vld;
output  [31:0] local_kernel_22_01134_out;
output   local_kernel_22_01134_out_ap_vld;
output  [31:0] local_kernel_21_01133_out;
output   local_kernel_21_01133_out_ap_vld;
output  [31:0] local_kernel_20_01132_out;
output   local_kernel_20_01132_out_ap_vld;
output  [31:0] local_kernel_19_01131_out;
output   local_kernel_19_01131_out_ap_vld;
output  [31:0] local_kernel_18_01130_out;
output   local_kernel_18_01130_out_ap_vld;
output  [31:0] local_kernel_17_01129_out;
output   local_kernel_17_01129_out_ap_vld;
output  [31:0] local_kernel_16_01128_out;
output   local_kernel_16_01128_out_ap_vld;
output  [31:0] local_kernel_15_01127_out;
output   local_kernel_15_01127_out_ap_vld;
output  [31:0] local_kernel_14_01126_out;
output   local_kernel_14_01126_out_ap_vld;
output  [31:0] local_kernel_13_01125_out;
output   local_kernel_13_01125_out_ap_vld;
output  [31:0] local_kernel_12_01124_out;
output   local_kernel_12_01124_out_ap_vld;
output  [31:0] local_kernel_11_01123_out;
output   local_kernel_11_01123_out_ap_vld;
output  [31:0] local_kernel_10_01122_out;
output   local_kernel_10_01122_out_ap_vld;
output  [31:0] local_kernel_9_01121_out;
output   local_kernel_9_01121_out_ap_vld;
output  [31:0] local_kernel_8_01120_out;
output   local_kernel_8_01120_out_ap_vld;
output  [31:0] local_kernel_7_01119_out;
output   local_kernel_7_01119_out_ap_vld;
output  [31:0] local_kernel_6_01118_out;
output   local_kernel_6_01118_out_ap_vld;
output  [31:0] local_kernel_5_01117_out;
output   local_kernel_5_01117_out_ap_vld;
output  [31:0] local_kernel_4_01116_out;
output   local_kernel_4_01116_out_ap_vld;
output  [31:0] local_kernel_3_01115_out;
output   local_kernel_3_01115_out_ap_vld;
output  [31:0] local_kernel_2_01114_out;
output   local_kernel_2_01114_out_ap_vld;
output  [31:0] local_kernel_1_01113_out;
output   local_kernel_1_01113_out_ap_vld;
output  [31:0] local_kernel_0_01112_out;
output   local_kernel_0_01112_out_ap_vld;

reg ap_idle;
reg kernel_ce0;
reg local_kernel_24_01136_out_ap_vld;
reg local_kernel_23_01135_out_ap_vld;
reg local_kernel_22_01134_out_ap_vld;
reg local_kernel_21_01133_out_ap_vld;
reg local_kernel_20_01132_out_ap_vld;
reg local_kernel_19_01131_out_ap_vld;
reg local_kernel_18_01130_out_ap_vld;
reg local_kernel_17_01129_out_ap_vld;
reg local_kernel_16_01128_out_ap_vld;
reg local_kernel_15_01127_out_ap_vld;
reg local_kernel_14_01126_out_ap_vld;
reg local_kernel_13_01125_out_ap_vld;
reg local_kernel_12_01124_out_ap_vld;
reg local_kernel_11_01123_out_ap_vld;
reg local_kernel_10_01122_out_ap_vld;
reg local_kernel_9_01121_out_ap_vld;
reg local_kernel_8_01120_out_ap_vld;
reg local_kernel_7_01119_out_ap_vld;
reg local_kernel_6_01118_out_ap_vld;
reg local_kernel_5_01117_out_ap_vld;
reg local_kernel_4_01116_out_ap_vld;
reg local_kernel_3_01115_out_ap_vld;
reg local_kernel_2_01114_out_ap_vld;
reg local_kernel_1_01113_out_ap_vld;
reg local_kernel_0_01112_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_438_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] i_1_reg_846;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] trunc_ln35_cast_fu_450_p1;
wire    ap_block_pp0_stage0;
reg   [4:0] i_fu_138;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
wire   [4:0] add_ln33_fu_444_p2;
reg   [31:0] local_kernel_1_fu_142;
wire   [31:0] local_kernel_1_26_fu_460_p1;
reg   [31:0] local_kernel_1_1_fu_146;
reg   [31:0] local_kernel_1_2_fu_150;
reg   [31:0] local_kernel_1_3_fu_154;
reg   [31:0] local_kernel_1_4_fu_158;
reg   [31:0] local_kernel_1_5_fu_162;
reg   [31:0] local_kernel_1_6_fu_166;
reg   [31:0] local_kernel_1_7_fu_170;
reg   [31:0] local_kernel_1_8_fu_174;
reg   [31:0] local_kernel_1_9_fu_178;
reg   [31:0] local_kernel_1_10_fu_182;
reg   [31:0] local_kernel_1_11_fu_186;
reg   [31:0] local_kernel_1_12_fu_190;
reg   [31:0] local_kernel_1_13_fu_194;
reg   [31:0] local_kernel_1_14_fu_198;
reg   [31:0] local_kernel_1_15_fu_202;
reg   [31:0] local_kernel_1_16_fu_206;
reg   [31:0] local_kernel_1_17_fu_210;
reg   [31:0] local_kernel_1_18_fu_214;
reg   [31:0] local_kernel_1_19_fu_218;
reg   [31:0] local_kernel_1_20_fu_222;
reg   [31:0] local_kernel_1_21_fu_226;
reg   [31:0] local_kernel_1_22_fu_230;
reg   [31:0] local_kernel_1_23_fu_234;
reg   [31:0] local_kernel_1_24_fu_238;
wire    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv2d_stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_438_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_138 <= add_ln33_fu_444_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_138 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_reg_846 <= ap_sig_allocacmp_i_1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd10))) begin
        local_kernel_1_10_fu_182 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd11))) begin
        local_kernel_1_11_fu_186 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd12))) begin
        local_kernel_1_12_fu_190 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd13))) begin
        local_kernel_1_13_fu_194 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd14))) begin
        local_kernel_1_14_fu_198 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd15))) begin
        local_kernel_1_15_fu_202 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd16))) begin
        local_kernel_1_16_fu_206 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd17))) begin
        local_kernel_1_17_fu_210 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd18))) begin
        local_kernel_1_18_fu_214 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd19))) begin
        local_kernel_1_19_fu_218 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd1))) begin
        local_kernel_1_1_fu_146 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd20))) begin
        local_kernel_1_20_fu_222 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd21))) begin
        local_kernel_1_21_fu_226 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd22))) begin
        local_kernel_1_22_fu_230 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd23))) begin
        local_kernel_1_23_fu_234 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & ((i_1_reg_846 == 5'd24) | ((i_1_reg_846 == 5'd25) | ((i_1_reg_846 == 5'd26) | ((i_1_reg_846 == 5'd27) | ((i_1_reg_846 == 5'd28) | ((i_1_reg_846 == 5'd29) | ((i_1_reg_846 == 5'd30) | (i_1_reg_846 == 5'd31)))))))))) begin
        local_kernel_1_24_fu_238 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd2))) begin
        local_kernel_1_2_fu_150 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd3))) begin
        local_kernel_1_3_fu_154 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd4))) begin
        local_kernel_1_4_fu_158 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd5))) begin
        local_kernel_1_5_fu_162 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd6))) begin
        local_kernel_1_6_fu_166 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd7))) begin
        local_kernel_1_7_fu_170 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd8))) begin
        local_kernel_1_8_fu_174 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd9))) begin
        local_kernel_1_9_fu_178 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (i_1_reg_846 == 5'd0))) begin
        local_kernel_1_fu_142 <= local_kernel_1_26_fu_460_p1;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_138;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_0_01112_out_ap_vld = 1'b1;
    end else begin
        local_kernel_0_01112_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_10_01122_out_ap_vld = 1'b1;
    end else begin
        local_kernel_10_01122_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_11_01123_out_ap_vld = 1'b1;
    end else begin
        local_kernel_11_01123_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_12_01124_out_ap_vld = 1'b1;
    end else begin
        local_kernel_12_01124_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_13_01125_out_ap_vld = 1'b1;
    end else begin
        local_kernel_13_01125_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_14_01126_out_ap_vld = 1'b1;
    end else begin
        local_kernel_14_01126_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_15_01127_out_ap_vld = 1'b1;
    end else begin
        local_kernel_15_01127_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_16_01128_out_ap_vld = 1'b1;
    end else begin
        local_kernel_16_01128_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_17_01129_out_ap_vld = 1'b1;
    end else begin
        local_kernel_17_01129_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_18_01130_out_ap_vld = 1'b1;
    end else begin
        local_kernel_18_01130_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_19_01131_out_ap_vld = 1'b1;
    end else begin
        local_kernel_19_01131_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_1_01113_out_ap_vld = 1'b1;
    end else begin
        local_kernel_1_01113_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_20_01132_out_ap_vld = 1'b1;
    end else begin
        local_kernel_20_01132_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_21_01133_out_ap_vld = 1'b1;
    end else begin
        local_kernel_21_01133_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_22_01134_out_ap_vld = 1'b1;
    end else begin
        local_kernel_22_01134_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_23_01135_out_ap_vld = 1'b1;
    end else begin
        local_kernel_23_01135_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_24_01136_out_ap_vld = 1'b1;
    end else begin
        local_kernel_24_01136_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_2_01114_out_ap_vld = 1'b1;
    end else begin
        local_kernel_2_01114_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_3_01115_out_ap_vld = 1'b1;
    end else begin
        local_kernel_3_01115_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_4_01116_out_ap_vld = 1'b1;
    end else begin
        local_kernel_4_01116_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_5_01117_out_ap_vld = 1'b1;
    end else begin
        local_kernel_5_01117_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_6_01118_out_ap_vld = 1'b1;
    end else begin
        local_kernel_6_01118_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_7_01119_out_ap_vld = 1'b1;
    end else begin
        local_kernel_7_01119_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_8_01120_out_ap_vld = 1'b1;
    end else begin
        local_kernel_8_01120_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_438_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        local_kernel_9_01121_out_ap_vld = 1'b1;
    end else begin
        local_kernel_9_01121_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_444_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln33_fu_438_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign kernel_address0 = trunc_ln35_cast_fu_450_p1;

assign local_kernel_0_01112_out = local_kernel_1_fu_142;

assign local_kernel_10_01122_out = local_kernel_1_10_fu_182;

assign local_kernel_11_01123_out = local_kernel_1_11_fu_186;

assign local_kernel_12_01124_out = local_kernel_1_12_fu_190;

assign local_kernel_13_01125_out = local_kernel_1_13_fu_194;

assign local_kernel_14_01126_out = local_kernel_1_14_fu_198;

assign local_kernel_15_01127_out = local_kernel_1_15_fu_202;

assign local_kernel_16_01128_out = local_kernel_1_16_fu_206;

assign local_kernel_17_01129_out = local_kernel_1_17_fu_210;

assign local_kernel_18_01130_out = local_kernel_1_18_fu_214;

assign local_kernel_19_01131_out = local_kernel_1_19_fu_218;

assign local_kernel_1_01113_out = local_kernel_1_1_fu_146;

assign local_kernel_1_26_fu_460_p1 = kernel_q0;

assign local_kernel_20_01132_out = local_kernel_1_20_fu_222;

assign local_kernel_21_01133_out = local_kernel_1_21_fu_226;

assign local_kernel_22_01134_out = local_kernel_1_22_fu_230;

assign local_kernel_23_01135_out = local_kernel_1_23_fu_234;

assign local_kernel_24_01136_out = local_kernel_1_24_fu_238;

assign local_kernel_2_01114_out = local_kernel_1_2_fu_150;

assign local_kernel_3_01115_out = local_kernel_1_3_fu_154;

assign local_kernel_4_01116_out = local_kernel_1_4_fu_158;

assign local_kernel_5_01117_out = local_kernel_1_5_fu_162;

assign local_kernel_6_01118_out = local_kernel_1_6_fu_166;

assign local_kernel_7_01119_out = local_kernel_1_7_fu_170;

assign local_kernel_8_01120_out = local_kernel_1_8_fu_174;

assign local_kernel_9_01121_out = local_kernel_1_9_fu_178;

assign trunc_ln35_cast_fu_450_p1 = ap_sig_allocacmp_i_1;

endmodule //conv2d_stream_conv2d_stream_Pipeline_localKernel
