-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_local_block : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_stream_conv2d_stream,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=12.650000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1881,HLS_SYN_LUT=2153,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_local_deadlock : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal kernel_ce0 : STD_LOGIC;
    signal kernel_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cols_read_reg_374 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_read_reg_381 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln36_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal kernel_load_reg_432 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal kernel_load_1_reg_442 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal kernel_load_2_reg_452 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal kernel_load_3_reg_462 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal kernel_load_4_reg_472 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal kernel_load_5_reg_482 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal kernel_load_6_reg_492 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal kernel_load_7_reg_502 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal padded_cols_fu_315_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_cols_reg_512 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln47_fu_333_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_reg_517 : STD_LOGIC_VECTOR (63 downto 0);
    signal kernel_load_8_reg_522 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal sub132_fu_367_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub132_reg_545 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_V_ce0 : STD_LOGIC;
    signal line_buf_V_we0 : STD_LOGIC;
    signal line_buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buf_V_ce1 : STD_LOGIC;
    signal line_buf_V_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buf_V_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_V_1_ce0 : STD_LOGIC;
    signal line_buf_V_1_we0 : STD_LOGIC;
    signal line_buf_V_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal line_buf_V_1_ce1 : STD_LOGIC;
    signal line_buf_V_1_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_2_promoted462540_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_2_promoted462540_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_2_promoted457532_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_2_promoted457532_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_1_promoted454528_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_1_promoted454528_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_1_promoted449520_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_1_promoted449520_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_promoted446515_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_promoted446515_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_promoted441507_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_promoted441507_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal icmp_ln36_fu_309_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_rows_fu_320_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln47_fu_333_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln47_fu_333_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul131_fu_363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal mul_ln47_fu_333_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_fu_333_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_55_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        line_buf_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_ce0 : OUT STD_LOGIC;
        line_buf_V_we0 : OUT STD_LOGIC;
        line_buf_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        line_buf_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_1_ce0 : OUT STD_LOGIC;
        line_buf_V_1_we0 : OUT STD_LOGIC;
        line_buf_V_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        arrayidx6315_2_promoted462540_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx6315_2_promoted462540_out_ap_vld : OUT STD_LOGIC;
        arrayidx5713_2_promoted457532_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_2_promoted457532_out_ap_vld : OUT STD_LOGIC;
        arrayidx6315_1_promoted454528_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx6315_1_promoted454528_out_ap_vld : OUT STD_LOGIC;
        arrayidx5713_1_promoted449520_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_1_promoted449520_out_ap_vld : OUT STD_LOGIC;
        arrayidx6315_promoted446515_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx6315_promoted446515_out_ap_vld : OUT STD_LOGIC;
        arrayidx5713_promoted441507_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_promoted441507_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        arrayidx6315_2_promoted462540_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_2_promoted457532_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        arrayidx6315_1_promoted454528_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_1_promoted449520_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        arrayidx6315_promoted446515_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        arrayidx5713_promoted441507_reload : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln66 : IN STD_LOGIC_VECTOR (31 downto 0);
        padded_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln47 : IN STD_LOGIC_VECTOR (63 downto 0);
        line_buf_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_ce0 : OUT STD_LOGIC;
        line_buf_V_we0 : OUT STD_LOGIC;
        line_buf_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        line_buf_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_ce1 : OUT STD_LOGIC;
        line_buf_V_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        line_buf_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_1_ce0 : OUT STD_LOGIC;
        line_buf_V_1_we0 : OUT STD_LOGIC;
        line_buf_V_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        line_buf_V_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_V_1_ce1 : OUT STD_LOGIC;
        line_buf_V_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1168 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_3 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_4 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_5 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_6 : IN STD_LOGIC_VECTOR (15 downto 0);
        sext_ln1245_7 : IN STD_LOGIC_VECTOR (15 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        sub132 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_stream_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component conv2d_stream_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_line_buf_V_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component conv2d_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : IN STD_LOGIC;
        kernel_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_local_deadlock : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line_buf_V_U : component conv2d_stream_line_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 130,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_V_address0,
        ce0 => line_buf_V_ce0,
        we0 => line_buf_V_we0,
        d0 => line_buf_V_d0,
        address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address1,
        ce1 => line_buf_V_ce1,
        q1 => line_buf_V_q1);

    line_buf_V_1_U : component conv2d_stream_line_buf_V_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 130,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_V_1_address0,
        ce0 => line_buf_V_1_ce0,
        we0 => line_buf_V_1_we0,
        d0 => line_buf_V_1_d0,
        address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address1,
        ce1 => line_buf_V_1_ce1,
        q1 => line_buf_V_1_q1);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_55_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_ready,
        line_buf_V_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_address0,
        line_buf_V_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_ce0,
        line_buf_V_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_we0,
        line_buf_V_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_d0,
        line_buf_V_1_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_address0,
        line_buf_V_1_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_ce0,
        line_buf_V_1_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_we0,
        line_buf_V_1_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_d0);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_ready,
        arrayidx6315_2_promoted462540_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_2_promoted462540_out,
        arrayidx6315_2_promoted462540_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_2_promoted462540_out_ap_vld,
        arrayidx5713_2_promoted457532_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_2_promoted457532_out,
        arrayidx5713_2_promoted457532_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_2_promoted457532_out_ap_vld,
        arrayidx6315_1_promoted454528_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_1_promoted454528_out,
        arrayidx6315_1_promoted454528_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_1_promoted454528_out_ap_vld,
        arrayidx5713_1_promoted449520_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_1_promoted449520_out,
        arrayidx5713_1_promoted449520_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_1_promoted449520_out_ap_vld,
        arrayidx6315_promoted446515_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_promoted446515_out,
        arrayidx6315_promoted446515_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_promoted446515_out_ap_vld,
        arrayidx5713_promoted441507_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_promoted441507_out,
        arrayidx5713_promoted441507_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_promoted441507_out_ap_vld);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TREADY,
        arrayidx6315_2_promoted462540_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_2_promoted462540_out,
        arrayidx5713_2_promoted457532_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_2_promoted457532_out,
        arrayidx6315_1_promoted454528_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_1_promoted454528_out,
        arrayidx5713_1_promoted449520_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_1_promoted449520_out,
        arrayidx6315_promoted446515_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx6315_promoted446515_out,
        arrayidx5713_promoted441507_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_arrayidx5713_promoted441507_out,
        sext_ln66 => rows_read_reg_381,
        padded_cols => padded_cols_reg_512,
        mul_ln47 => mul_ln47_reg_517,
        line_buf_V_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address0,
        line_buf_V_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce0,
        line_buf_V_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_we0,
        line_buf_V_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_d0,
        line_buf_V_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address1,
        line_buf_V_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce1,
        line_buf_V_q1 => line_buf_V_q1,
        line_buf_V_1_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address0,
        line_buf_V_1_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce0,
        line_buf_V_1_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_we0,
        line_buf_V_1_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_d0,
        line_buf_V_1_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address1,
        line_buf_V_1_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce1,
        line_buf_V_1_q1 => line_buf_V_1_q1,
        sext_ln1168 => kernel_load_reg_432,
        sext_ln1245 => kernel_load_1_reg_442,
        sext_ln1245_1 => kernel_load_2_reg_452,
        sext_ln1245_2 => kernel_load_3_reg_462,
        sext_ln1245_3 => kernel_load_4_reg_472,
        sext_ln1245_4 => kernel_load_5_reg_482,
        sext_ln1245_5 => kernel_load_6_reg_492,
        sext_ln1245_6 => kernel_load_7_reg_502,
        sext_ln1245_7 => kernel_load_8_reg_522,
        cols => cols_read_reg_374,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        sub132 => sub132_reg_545,
        out_stream_TDATA => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        out_stream_TKEEP => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TSTRB,
        out_stream_TUSER => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TUSER,
        out_stream_TLAST => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TLAST,
        out_stream_TID => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TID,
        out_stream_TDEST => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDEST);

    CTRL_s_axi_U : component conv2d_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rows => rows,
        cols => cols,
        kernel_address0 => kernel_address0,
        kernel_ce0 => kernel_ce0,
        kernel_q0 => kernel_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_local_deadlock => ap_local_deadlock);

    mul_32ns_32ns_64_1_1_U58 : component conv2d_stream_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => mul_ln47_fu_333_p0,
        din1 => mul_ln47_fu_333_p1,
        dout => mul_ln47_fu_333_p2);

    mul_32s_32s_32_1_1_U59 : component conv2d_stream_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => cols_read_reg_374,
        din1 => rows_read_reg_381,
        dout => mul131_fu_363_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDATA,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TKEEP,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TSTRB,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TUSER,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TLAST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TID,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TDEST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln36_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln36_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cols_read_reg_374 <= cols;
                rows_read_reg_381 <= rows;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                kernel_load_1_reg_442 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                kernel_load_2_reg_452 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                kernel_load_3_reg_462 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                kernel_load_4_reg_472 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                kernel_load_5_reg_482 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                kernel_load_6_reg_492 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                kernel_load_7_reg_502 <= kernel_q0;
                mul_ln47_reg_517 <= mul_ln47_fu_333_p2;
                padded_cols_reg_512 <= padded_cols_fu_315_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                kernel_load_8_reg_522 <= kernel_q0;
                sub132_reg_545 <= sub132_fu_367_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                kernel_load_reg_432 <= kernel_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln36_fu_309_p2, ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done, ap_CS_fsm_state11, ap_block_state2_on_subcall_done, ap_CS_fsm_state12, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln36_fu_309_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                elsif (((icmp_ln36_fu_309_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state11) and (grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done)
    begin
        if ((grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state2_on_subcall_done_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_done, grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_done = ap_const_logic_0) or (grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state12, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_lv1_0;

    ap_ready_assign_proc : process(ap_CS_fsm_state12, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_60_3_VITIS_LOOP_61_4_fu_244_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state11);
    icmp_ln36_fu_309_p0 <= cols;
    icmp_ln36_fu_309_p2 <= "1" when (signed(icmp_ln36_fu_309_p0) > signed(ap_const_lv32_80)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_in_stream_TREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    kernel_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            kernel_address0 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            kernel_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            kernel_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            kernel_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            kernel_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            kernel_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            kernel_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            kernel_address0 <= ap_const_lv64_1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            kernel_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            kernel_address0 <= "XXXX";
        end if; 
    end process;


    kernel_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then 
            kernel_ce0 <= ap_const_logic_1;
        else 
            kernel_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_1_address0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_address0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_1_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_1_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_address0;
        else 
            line_buf_V_1_address0 <= "XXXXXXXX";
        end if; 
    end process;


    line_buf_V_1_ce0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_ce0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_1_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_1_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_ce0;
        else 
            line_buf_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_1_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce1, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_1_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_ce1;
        else 
            line_buf_V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_1_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_d0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_1_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_1_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_d0;
        else 
            line_buf_V_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_V_1_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_we0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_we0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_1_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_1_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_1_we0;
        else 
            line_buf_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_address0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_address0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_address0;
        else 
            line_buf_V_address0 <= "XXXXXXXX";
        end if; 
    end process;


    line_buf_V_ce0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_ce0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_ce0;
        else 
            line_buf_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce1, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_ce1;
        else 
            line_buf_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_V_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_d0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_d0;
        else 
            line_buf_V_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_V_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_we0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_we0, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            line_buf_V_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_line_buf_V_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_V_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_55_2_fu_236_line_buf_V_we0;
        else 
            line_buf_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln47_fu_333_p0 <= mul_ln47_fu_333_p00(32 - 1 downto 0);
    mul_ln47_fu_333_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(padded_rows_fu_320_p2),64));
    mul_ln47_fu_333_p1 <= mul_ln47_fu_333_p10(32 - 1 downto 0);
    mul_ln47_fu_333_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(padded_cols_fu_315_p2),64));
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_254_out_stream_TVALID;
    padded_cols_fu_315_p2 <= std_logic_vector(unsigned(cols_read_reg_374) + unsigned(ap_const_lv32_2));
    padded_rows_fu_320_p2 <= std_logic_vector(unsigned(rows_read_reg_381) + unsigned(ap_const_lv32_2));
    sub132_fu_367_p2 <= std_logic_vector(unsigned(mul131_fu_363_p2) + unsigned(ap_const_lv32_FFFFFFFF));
end behav;
