-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_stream_conv2d_stream,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=13.081000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=6146,HLS_SYN_LUT=9079,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_read_reg_360 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_read_reg_367 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_cols_fu_265_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_cols_reg_467 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln39_fu_283_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln39_reg_472 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub105_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub105_reg_522 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal line_buf_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_0_ce0 : STD_LOGIC;
    signal line_buf_0_we0 : STD_LOGIC;
    signal line_buf_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_0_ce1 : STD_LOGIC;
    signal line_buf_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal line_buf_1_ce0 : STD_LOGIC;
    signal line_buf_1_we0 : STD_LOGIC;
    signal line_buf_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_1_ce1 : STD_LOGIC;
    signal line_buf_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_8_0222_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_8_0222_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_7_0221_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_7_0221_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_6_0220_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_6_0220_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_5_0219_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_5_0219_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_4_0218_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_4_0218_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_3_0217_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_3_0217_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_2_0216_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_2_0216_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_1_0215_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_1_0215_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_0_0214_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_0_0214_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_2_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_2_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_1_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_1_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_2_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_2_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_1_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_1_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_2_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_2_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_1_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_1_1_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln29_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln29_fu_259_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_rows_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln39_fu_283_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln39_fu_283_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul104_fu_349_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal mul_ln39_fu_283_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln39_fu_283_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_33_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : OUT STD_LOGIC;
        kernel_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_8_0222_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_8_0222_out_ap_vld : OUT STD_LOGIC;
        local_kernel_7_0221_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_7_0221_out_ap_vld : OUT STD_LOGIC;
        local_kernel_6_0220_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_6_0220_out_ap_vld : OUT STD_LOGIC;
        local_kernel_5_0219_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_5_0219_out_ap_vld : OUT STD_LOGIC;
        local_kernel_4_0218_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_4_0218_out_ap_vld : OUT STD_LOGIC;
        local_kernel_3_0217_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_3_0217_out_ap_vld : OUT STD_LOGIC;
        local_kernel_2_0216_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_2_0216_out_ap_vld : OUT STD_LOGIC;
        local_kernel_1_0215_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_1_0215_out_ap_vld : OUT STD_LOGIC;
        local_kernel_0_0214_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_0_0214_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_47_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        line_buf_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_0_ce0 : OUT STD_LOGIC;
        line_buf_0_we0 : OUT STD_LOGIC;
        line_buf_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_1_ce0 : OUT STD_LOGIC;
        line_buf_1_we0 : OUT STD_LOGIC;
        line_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_2_2_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_2_2_1_out_ap_vld : OUT STD_LOGIC;
        window_2_1_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_2_1_1_out_ap_vld : OUT STD_LOGIC;
        window_1_2_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_1_2_1_out_ap_vld : OUT STD_LOGIC;
        window_1_1_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_1_1_1_out_ap_vld : OUT STD_LOGIC;
        window_0_2_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_0_2_1_out_ap_vld : OUT STD_LOGIC;
        window_0_1_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        window_0_1_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        window_2_2_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        window_2_1_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        window_1_2_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        window_1_1_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        window_0_2_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        window_0_1_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln66 : IN STD_LOGIC_VECTOR (31 downto 0);
        padded_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        mul_ln39 : IN STD_LOGIC_VECTOR (63 downto 0);
        line_buf_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_0_ce0 : OUT STD_LOGIC;
        line_buf_0_we0 : OUT STD_LOGIC;
        line_buf_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_0_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_0_ce1 : OUT STD_LOGIC;
        line_buf_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        line_buf_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_1_ce0 : OUT STD_LOGIC;
        line_buf_1_we0 : OUT STD_LOGIC;
        line_buf_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        line_buf_1_ce1 : OUT STD_LOGIC;
        line_buf_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_0_0214_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_1_0215_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_2_0216_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_3_0217_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_4_0218_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_5_0219_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_6_0220_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_7_0221_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_8_0222_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        sub105 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_stream_mul_32ns_32ns_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component conv2d_stream_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_line_buf_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : IN STD_LOGIC;
        kernel_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component conv2d_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    line_buf_0_U : component conv2d_stream_line_buf_0
    generic map (
        DataWidth => 32,
        AddressRange => 130,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_0_address0,
        ce0 => line_buf_0_ce0,
        we0 => line_buf_0_we0,
        d0 => line_buf_0_d0,
        address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address1,
        ce1 => line_buf_0_ce1,
        q1 => line_buf_0_q1);

    line_buf_1_U : component conv2d_stream_line_buf_0
    generic map (
        DataWidth => 32,
        AddressRange => 130,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_1_address0,
        ce0 => line_buf_1_ce0,
        we0 => line_buf_1_we0,
        d0 => line_buf_1_d0,
        address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address1,
        ce1 => line_buf_1_ce1,
        q1 => line_buf_1_q1);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_33_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_ready,
        kernel_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_address0,
        kernel_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_ce0,
        kernel_q0 => kernel_q0,
        local_kernel_8_0222_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_8_0222_out,
        local_kernel_8_0222_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_8_0222_out_ap_vld,
        local_kernel_7_0221_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_7_0221_out,
        local_kernel_7_0221_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_7_0221_out_ap_vld,
        local_kernel_6_0220_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_6_0220_out,
        local_kernel_6_0220_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_6_0220_out_ap_vld,
        local_kernel_5_0219_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_5_0219_out,
        local_kernel_5_0219_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_5_0219_out_ap_vld,
        local_kernel_4_0218_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_4_0218_out,
        local_kernel_4_0218_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_4_0218_out_ap_vld,
        local_kernel_3_0217_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_3_0217_out,
        local_kernel_3_0217_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_3_0217_out_ap_vld,
        local_kernel_2_0216_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_2_0216_out,
        local_kernel_2_0216_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_2_0216_out_ap_vld,
        local_kernel_1_0215_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_1_0215_out,
        local_kernel_1_0215_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_1_0215_out_ap_vld,
        local_kernel_0_0214_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_0_0214_out,
        local_kernel_0_0214_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_0_0214_out_ap_vld);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_47_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_ready,
        line_buf_0_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_address0,
        line_buf_0_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_ce0,
        line_buf_0_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_we0,
        line_buf_0_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_d0,
        line_buf_1_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_address0,
        line_buf_1_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_ce0,
        line_buf_1_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_we0,
        line_buf_1_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_d0);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_ready,
        window_2_2_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_2_1_out,
        window_2_2_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_2_1_out_ap_vld,
        window_2_1_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_1_1_out,
        window_2_1_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_1_1_out_ap_vld,
        window_1_2_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_2_1_out,
        window_1_2_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_2_1_out_ap_vld,
        window_1_1_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_1_1_out,
        window_1_1_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_1_1_out_ap_vld,
        window_0_2_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_2_1_out,
        window_0_2_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_2_1_out_ap_vld,
        window_0_1_1_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_1_1_out,
        window_0_1_1_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_1_1_out_ap_vld);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        out_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TREADY,
        window_2_2_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_2_1_out,
        window_2_1_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_2_1_1_out,
        window_1_2_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_2_1_out,
        window_1_1_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_1_1_1_out,
        window_0_2_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_2_1_out,
        window_0_1_1_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_window_0_1_1_out,
        sext_ln66 => rows_read_reg_367,
        padded_cols => padded_cols_reg_467,
        mul_ln39 => mul_ln39_reg_472,
        line_buf_0_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address0,
        line_buf_0_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce0,
        line_buf_0_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_we0,
        line_buf_0_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_d0,
        line_buf_0_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address1,
        line_buf_0_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce1,
        line_buf_0_q1 => line_buf_0_q1,
        line_buf_1_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address0,
        line_buf_1_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce0,
        line_buf_1_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_we0,
        line_buf_1_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_d0,
        line_buf_1_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address1,
        line_buf_1_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce1,
        line_buf_1_q1 => line_buf_1_q1,
        local_kernel_0_0214_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_0_0214_out,
        local_kernel_1_0215_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_1_0215_out,
        local_kernel_2_0216_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_2_0216_out,
        local_kernel_3_0217_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_3_0217_out,
        local_kernel_4_0218_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_4_0218_out,
        local_kernel_5_0219_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_5_0219_out,
        local_kernel_6_0220_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_6_0220_out,
        local_kernel_7_0221_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_7_0221_out,
        local_kernel_8_0222_reload => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_local_kernel_8_0222_out,
        cols => cols_read_reg_360,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        sub105 => sub105_reg_522,
        out_stream_TDATA => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        out_stream_TKEEP => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TSTRB,
        out_stream_TUSER => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TUSER,
        out_stream_TLAST => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TLAST,
        out_stream_TID => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TID,
        out_stream_TDEST => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDEST);

    CTRL_s_axi_U : component conv2d_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rows => rows,
        cols => cols,
        kernel_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_address0,
        kernel_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_kernel_ce0,
        kernel_q0 => kernel_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_32ns_32ns_64_1_1_U77 : component conv2d_stream_mul_32ns_32ns_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => mul_ln39_fu_283_p0,
        din1 => mul_ln39_fu_283_p1,
        dout => mul_ln39_fu_283_p2);

    mul_32s_32s_32_1_1_U78 : component conv2d_stream_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => cols_read_reg_360,
        din1 => rows_read_reg_367,
        dout => mul104_fu_349_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDATA,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TKEEP,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TSTRB,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TUSER,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TLAST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TID,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TDEST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln29_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln29_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln29_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cols_read_reg_360 <= cols;
                rows_read_reg_367 <= rows;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                mul_ln39_reg_472 <= mul_ln39_fu_283_p2;
                padded_cols_reg_467 <= padded_cols_fu_265_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                sub105_reg_522 <= sub105_fu_353_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done, icmp_ln29_fu_259_p2, ap_CS_fsm_state4, ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln29_fu_259_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((icmp_ln29_fu_259_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done)
    begin
        if ((grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_done, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_done, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_done = ap_const_logic_0) or (grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_done = ap_const_logic_0) or (grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_172_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_3_VITIS_LOOP_53_4_fu_195_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state4);
    icmp_ln29_fu_259_p0 <= cols;
    icmp_ln29_fu_259_p2 <= "1" when (signed(icmp_ln29_fu_259_p0) > signed(ap_const_lv32_80)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_in_stream_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_address0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_address0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_0_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_0_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_address0;
        else 
            line_buf_0_address0 <= "XXXXXXXX";
        end if; 
    end process;


    line_buf_0_ce0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_ce0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_0_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_0_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_ce0;
        else 
            line_buf_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_0_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_ce1;
        else 
            line_buf_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_0_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_d0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_0_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_0_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_d0;
        else 
            line_buf_0_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_0_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_we0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_0_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_0_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_0_we0;
        else 
            line_buf_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_address0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_address0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_1_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_1_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_address0;
        else 
            line_buf_1_address0 <= "XXXXXXXX";
        end if; 
    end process;


    line_buf_1_ce0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_ce0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_1_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_1_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_ce0;
        else 
            line_buf_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_ce1_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_1_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_ce1;
        else 
            line_buf_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_1_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_d0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_1_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_1_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_d0;
        else 
            line_buf_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_1_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_we0, grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            line_buf_1_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_line_buf_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_1_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_47_2_fu_187_line_buf_1_we0;
        else 
            line_buf_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln39_fu_283_p0 <= mul_ln39_fu_283_p00(32 - 1 downto 0);
    mul_ln39_fu_283_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(padded_rows_fu_270_p2),64));
    mul_ln39_fu_283_p1 <= mul_ln39_fu_283_p10(32 - 1 downto 0);
    mul_ln39_fu_283_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(padded_cols_fu_265_p2),64));
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6_fu_205_out_stream_TVALID;
    padded_cols_fu_265_p2 <= std_logic_vector(unsigned(cols_read_reg_360) + unsigned(ap_const_lv32_2));
    padded_rows_fu_270_p2 <= std_logic_vector(unsigned(rows_read_reg_367) + unsigned(ap_const_lv32_2));
    sub105_fu_353_p2 <= std_logic_vector(unsigned(mul104_fu_349_p2) + unsigned(ap_const_lv32_FFFFFFFF));
end behav;
