// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        out_stream_TREADY,
        window_2_2_1_reload,
        window_2_1_1_reload,
        window_1_2_1_reload,
        window_1_1_1_reload,
        window_0_2_1_reload,
        window_0_1_1_reload,
        sext_ln66,
        padded_cols,
        mul_ln39,
        line_buf_0_address0,
        line_buf_0_ce0,
        line_buf_0_we0,
        line_buf_0_d0,
        line_buf_0_address1,
        line_buf_0_ce1,
        line_buf_0_q1,
        line_buf_1_address0,
        line_buf_1_ce0,
        line_buf_1_we0,
        line_buf_1_d0,
        line_buf_1_address1,
        line_buf_1_ce1,
        line_buf_1_q1,
        local_kernel_0_0214_reload,
        local_kernel_1_0215_reload,
        local_kernel_2_0216_reload,
        local_kernel_3_0217_reload,
        local_kernel_4_0218_reload,
        local_kernel_5_0219_reload,
        local_kernel_6_0220_reload,
        local_kernel_7_0221_reload,
        local_kernel_8_0222_reload,
        cols,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        sub105,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [31:0] window_2_2_1_reload;
input  [31:0] window_2_1_1_reload;
input  [31:0] window_1_2_1_reload;
input  [31:0] window_1_1_1_reload;
input  [31:0] window_0_2_1_reload;
input  [31:0] window_0_1_1_reload;
input  [31:0] sext_ln66;
input  [31:0] padded_cols;
input  [63:0] mul_ln39;
output  [7:0] line_buf_0_address0;
output   line_buf_0_ce0;
output   line_buf_0_we0;
output  [31:0] line_buf_0_d0;
output  [7:0] line_buf_0_address1;
output   line_buf_0_ce1;
input  [31:0] line_buf_0_q1;
output  [7:0] line_buf_1_address0;
output   line_buf_1_ce0;
output   line_buf_1_we0;
output  [31:0] line_buf_1_d0;
output  [7:0] line_buf_1_address1;
output   line_buf_1_ce1;
input  [31:0] line_buf_1_q1;
input  [31:0] local_kernel_0_0214_reload;
input  [31:0] local_kernel_1_0215_reload;
input  [31:0] local_kernel_2_0216_reload;
input  [31:0] local_kernel_3_0217_reload;
input  [31:0] local_kernel_4_0218_reload;
input  [31:0] local_kernel_5_0219_reload;
input  [31:0] local_kernel_6_0220_reload;
input  [31:0] local_kernel_7_0221_reload;
input  [31:0] local_kernel_8_0222_reload;
input  [31:0] cols;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
input  [31:0] sub105;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

reg ap_idle;
reg line_buf_0_ce0;
reg line_buf_0_we0;
reg line_buf_0_ce1;
reg line_buf_1_ce0;
reg line_buf_1_we0;
reg line_buf_1_ce1;
reg in_stream_TREADY;
reg out_stream_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln66_fu_630_p2;
wire   [0:0] and_ln75_1_fu_788_p2;
reg    ap_predicate_op136_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
reg   [0:0] and_ln124_1_reg_1342;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter38_reg;
reg    ap_block_state40_pp0_stage0_iter39;
reg    ap_block_state40_io;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg   [31:0] new_pixel_2_reg_398;
reg   [31:0] new_pixel_2_reg_398_pp0_iter3_reg;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] new_pixel_2_reg_398_pp0_iter4_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter5_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter6_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter7_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter8_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter9_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter10_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter11_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter12_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter13_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter14_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter15_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter16_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter17_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter18_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter19_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter20_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter21_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter22_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter23_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter24_reg;
reg   [31:0] new_pixel_2_reg_398_pp0_iter25_reg;
wire  signed [32:0] sext_ln66_cast_fu_485_p1;
reg  signed [32:0] sext_ln66_cast_reg_1237;
wire   [7:0] select_ln66_fu_641_p3;
reg   [7:0] select_ln66_reg_1249;
wire  signed [31:0] add_ln66_1_fu_679_p2;
reg  signed [31:0] add_ln66_1_reg_1254;
wire   [0:0] select_ln66_3_fu_735_p3;
reg   [0:0] select_ln66_3_reg_1259;
wire   [8:0] zext_ln67_1_fu_757_p1;
reg   [8:0] zext_ln67_1_reg_1264;
wire   [31:0] new_pixel_fu_798_p1;
reg   [7:0] line_buf_0_addr_reg_1278;
wire   [0:0] addr_cmp42_fu_805_p2;
reg   [0:0] addr_cmp42_reg_1284;
reg   [7:0] line_buf_1_addr_reg_1289;
wire   [0:0] addr_cmp_fu_814_p2;
reg   [0:0] addr_cmp_reg_1295;
wire   [0:0] icmp_ln97_fu_830_p2;
reg   [0:0] icmp_ln97_reg_1300;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter2_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter3_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter4_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter5_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter6_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter7_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter8_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter9_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter10_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter11_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter12_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter13_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter14_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter15_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter16_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter17_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter18_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter19_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter20_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter21_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter22_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter23_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter24_reg;
reg   [0:0] icmp_ln97_reg_1300_pp0_iter25_reg;
wire   [0:0] icmp_ln97_1_fu_836_p2;
reg   [0:0] icmp_ln97_1_reg_1307;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter2_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter3_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter4_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter5_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter6_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter7_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter8_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter9_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter10_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter11_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter12_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter13_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter14_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter15_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter16_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter17_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter18_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter19_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter20_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter21_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter22_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter23_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter24_reg;
reg   [0:0] icmp_ln97_1_reg_1307_pp0_iter25_reg;
wire   [0:0] empty_18_fu_842_p2;
reg   [0:0] empty_18_reg_1314;
reg   [0:0] empty_18_reg_1314_pp0_iter2_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter3_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter4_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter5_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter6_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter7_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter8_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter9_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter10_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter11_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter12_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter13_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter14_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter15_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter16_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter17_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter18_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter19_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter20_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter21_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter22_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter23_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter24_reg;
reg   [0:0] empty_18_reg_1314_pp0_iter25_reg;
wire   [31:0] window_0_2_fu_882_p3;
reg   [31:0] window_0_2_reg_1321;
wire   [31:0] window_1_2_fu_892_p3;
reg   [31:0] window_1_2_reg_1326;
reg   [31:0] window_1_2_reg_1326_pp0_iter3_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter4_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter5_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter6_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter7_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter8_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter9_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter10_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter11_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter12_reg;
reg   [31:0] window_1_2_reg_1326_pp0_iter13_reg;
wire   [31:0] window_load_3_fu_925_p3;
wire   [0:0] and_ln124_1_fu_971_p2;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter3_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter4_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter5_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter6_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter7_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter8_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter9_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter10_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter11_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter12_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter13_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter14_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter15_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter16_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter17_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter18_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter19_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter20_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter21_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter22_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter23_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter24_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter25_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter26_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter27_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter28_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter29_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter30_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter31_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter32_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter33_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter34_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter35_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter36_reg;
reg   [0:0] and_ln124_1_reg_1342_pp0_iter37_reg;
wire   [31:0] add_ln129_fu_977_p2;
reg   [31:0] add_ln129_reg_1346;
wire   [31:0] grp_fu_448_p2;
reg   [31:0] mul_reg_1351;
wire   [31:0] grp_fu_452_p2;
reg   [31:0] mul92_s_reg_1356;
reg   [31:0] mul92_s_reg_1356_pp0_iter4_reg;
reg   [31:0] mul92_s_reg_1356_pp0_iter5_reg;
reg   [31:0] mul92_s_reg_1356_pp0_iter6_reg;
reg   [31:0] mul92_s_reg_1356_pp0_iter7_reg;
wire   [0:0] is_last_fu_993_p2;
reg   [0:0] is_last_reg_1361;
reg   [0:0] is_last_reg_1361_pp0_iter4_reg;
reg   [0:0] is_last_reg_1361_pp0_iter5_reg;
reg   [0:0] is_last_reg_1361_pp0_iter6_reg;
reg   [0:0] is_last_reg_1361_pp0_iter7_reg;
reg   [0:0] is_last_reg_1361_pp0_iter8_reg;
reg   [0:0] is_last_reg_1361_pp0_iter9_reg;
reg   [0:0] is_last_reg_1361_pp0_iter10_reg;
reg   [0:0] is_last_reg_1361_pp0_iter11_reg;
reg   [0:0] is_last_reg_1361_pp0_iter12_reg;
reg   [0:0] is_last_reg_1361_pp0_iter13_reg;
reg   [0:0] is_last_reg_1361_pp0_iter14_reg;
reg   [0:0] is_last_reg_1361_pp0_iter15_reg;
reg   [0:0] is_last_reg_1361_pp0_iter16_reg;
reg   [0:0] is_last_reg_1361_pp0_iter17_reg;
reg   [0:0] is_last_reg_1361_pp0_iter18_reg;
reg   [0:0] is_last_reg_1361_pp0_iter19_reg;
reg   [0:0] is_last_reg_1361_pp0_iter20_reg;
reg   [0:0] is_last_reg_1361_pp0_iter21_reg;
reg   [0:0] is_last_reg_1361_pp0_iter22_reg;
reg   [0:0] is_last_reg_1361_pp0_iter23_reg;
reg   [0:0] is_last_reg_1361_pp0_iter24_reg;
reg   [0:0] is_last_reg_1361_pp0_iter25_reg;
reg   [0:0] is_last_reg_1361_pp0_iter26_reg;
reg   [0:0] is_last_reg_1361_pp0_iter27_reg;
reg   [0:0] is_last_reg_1361_pp0_iter28_reg;
reg   [0:0] is_last_reg_1361_pp0_iter29_reg;
reg   [0:0] is_last_reg_1361_pp0_iter30_reg;
reg   [0:0] is_last_reg_1361_pp0_iter31_reg;
reg   [0:0] is_last_reg_1361_pp0_iter32_reg;
reg   [0:0] is_last_reg_1361_pp0_iter33_reg;
reg   [0:0] is_last_reg_1361_pp0_iter34_reg;
reg   [0:0] is_last_reg_1361_pp0_iter35_reg;
reg   [0:0] is_last_reg_1361_pp0_iter36_reg;
reg   [0:0] is_last_reg_1361_pp0_iter37_reg;
reg   [0:0] is_last_reg_1361_pp0_iter38_reg;
wire   [31:0] grp_fu_456_p2;
reg   [31:0] mul92_3_reg_1366;
reg   [31:0] mul92_3_reg_1366_pp0_iter5_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter6_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter7_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter8_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter9_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter10_reg;
reg   [31:0] mul92_3_reg_1366_pp0_iter11_reg;
wire   [31:0] grp_fu_411_p2;
reg   [31:0] acc_reg_1371;
wire   [31:0] grp_fu_416_p2;
reg   [31:0] acc_1_reg_1376;
wire   [31:0] window_load_6_fu_1018_p3;
wire   [31:0] grp_fu_420_p2;
reg   [31:0] acc_2_reg_1391;
wire   [31:0] grp_fu_460_p2;
reg   [31:0] mul92_1_reg_1396;
wire   [31:0] grp_fu_464_p2;
reg   [31:0] mul92_1_1_reg_1401;
reg   [31:0] mul92_1_1_reg_1401_pp0_iter16_reg;
reg   [31:0] mul92_1_1_reg_1401_pp0_iter17_reg;
reg   [31:0] mul92_1_1_reg_1401_pp0_iter18_reg;
reg   [31:0] mul92_1_1_reg_1401_pp0_iter19_reg;
wire   [31:0] grp_fu_468_p2;
reg   [31:0] mul92_1_2_reg_1406;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter16_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter17_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter18_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter19_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter20_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter21_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter22_reg;
reg   [31:0] mul92_1_2_reg_1406_pp0_iter23_reg;
wire   [31:0] grp_fu_424_p2;
reg   [31:0] acc_3_reg_1411;
wire   [31:0] grp_fu_428_p2;
reg   [31:0] acc_4_reg_1416;
wire   [31:0] window_load_9_fu_1056_p3;
wire   [31:0] grp_fu_432_p2;
reg   [31:0] acc_5_reg_1431;
wire   [31:0] grp_fu_472_p2;
reg   [31:0] mul92_2_reg_1436;
wire   [31:0] grp_fu_476_p2;
reg   [31:0] mul92_2_1_reg_1441;
reg   [31:0] mul92_2_1_reg_1441_pp0_iter28_reg;
reg   [31:0] mul92_2_1_reg_1441_pp0_iter29_reg;
reg   [31:0] mul92_2_1_reg_1441_pp0_iter30_reg;
reg   [31:0] mul92_2_1_reg_1441_pp0_iter31_reg;
wire   [31:0] grp_fu_480_p2;
reg   [31:0] mul92_2_2_reg_1446;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter28_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter29_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter30_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter31_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter32_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter33_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter34_reg;
reg   [31:0] mul92_2_2_reg_1446_pp0_iter35_reg;
wire   [31:0] grp_fu_436_p2;
reg   [31:0] acc_6_reg_1451;
wire   [31:0] grp_fu_440_p2;
reg   [31:0] acc_7_reg_1456;
wire   [31:0] ap_phi_reg_pp0_iter0_new_pixel_2_reg_398;
reg   [31:0] ap_phi_reg_pp0_iter1_new_pixel_2_reg_398;
reg   [31:0] ap_phi_reg_pp0_iter2_new_pixel_2_reg_398;
wire   [63:0] zext_ln67_fu_751_p1;
reg   [63:0] reuse_addr_reg39_fu_144;
wire    ap_loop_init;
reg   [31:0] reuse_reg38_fu_148;
reg   [63:0] reuse_addr_reg_fu_152;
reg   [31:0] reuse_reg_fu_156;
reg   [7:0] pj_fu_160;
wire   [7:0] add_ln67_fu_848_p2;
reg   [31:0] window_0_1_4_fu_164;
reg   [31:0] window_0_1_fu_168;
reg   [31:0] window_1_1_4_fu_172;
reg   [31:0] window_1_1_fu_176;
reg   [31:0] window_2_1_4_fu_180;
reg   [31:0] window_2_1_fu_184;
reg   [31:0] pi_fu_188;
wire   [31:0] select_ln66_4_fu_743_p3;
reg   [63:0] indvar_flatten13_fu_192;
wire   [63:0] add_ln66_fu_635_p2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_448_p0;
wire   [31:0] grp_fu_452_p0;
wire   [31:0] grp_fu_460_p0;
wire   [31:0] grp_fu_464_p0;
wire   [31:0] grp_fu_472_p0;
wire   [31:0] grp_fu_476_p0;
wire   [32:0] zext_ln66_fu_563_p1;
wire   [32:0] empty_fu_567_p2;
wire   [32:0] empty_17_fu_573_p2;
wire   [0:0] tmp_fu_590_p3;
wire   [0:0] notrhs_fu_585_p2;
wire   [0:0] notlhs_fu_579_p2;
wire   [0:0] notrhs2_fu_604_p2;
wire   [0:0] rev_fu_598_p2;
wire   [31:0] zext_ln67_2_fu_621_p1;
wire   [0:0] icmp_ln67_fu_625_p2;
wire   [31:0] add_ln66_2_fu_649_p2;
wire   [32:0] zext_ln66_1_fu_655_p1;
wire   [31:0] select_ln66_1_fu_671_p3;
wire   [32:0] p_mid1_fu_659_p2;
wire   [32:0] p_mid19_fu_665_p2;
wire   [0:0] tmp_1_fu_696_p3;
wire   [0:0] notrhs_mid1_fu_691_p2;
wire   [0:0] notlhs_mid1_fu_685_p2;
wire   [0:0] and_ln75_3_fu_715_p2;
wire   [0:0] and_ln75_fu_609_p2;
wire   [0:0] notrhs2_mid1_fu_710_p2;
wire   [0:0] rev37_fu_704_p2;
wire   [0:0] and_ln124_3_fu_729_p2;
wire   [0:0] and_ln124_fu_615_p2;
wire   [8:0] add_ln72_fu_761_p2;
wire  signed [31:0] sext_ln76_fu_767_p1;
wire  signed [31:0] icmp_ln76_1_fu_777_p1;
wire   [0:0] icmp_ln76_1_fu_777_p2;
wire   [0:0] icmp_ln76_fu_771_p2;
wire   [0:0] and_ln75_2_fu_782_p2;
wire   [0:0] select_ln66_2_fu_721_p3;
wire   [31:0] select_ln97_fu_918_p3;
wire   [8:0] add_ln123_fu_933_p2;
wire   [7:0] add_ln125_fu_942_p2;
wire   [0:0] tmp_3_fu_947_p3;
wire  signed [31:0] sext_ln125_fu_938_p1;
wire  signed [31:0] icmp_ln125_fu_961_p1;
wire   [0:0] xor_ln125_fu_955_p2;
wire   [0:0] and_ln124_2_fu_966_p2;
wire   [0:0] icmp_ln125_fu_961_p2;
wire   [31:0] mul_ln66_fu_869_p2;
wire   [31:0] select_ln97_1_fu_1011_p3;
wire   [31:0] select_ln97_2_fu_1049_p3;
wire   [31:0] grp_fu_444_p2;
reg    grp_fu_411_ce;
reg    grp_fu_416_ce;
reg    grp_fu_420_ce;
reg    grp_fu_424_ce;
reg    grp_fu_428_ce;
reg    grp_fu_432_ce;
reg    grp_fu_436_ce;
reg    grp_fu_440_ce;
reg    grp_fu_444_ce;
reg    grp_fu_448_ce;
reg    grp_fu_452_ce;
reg    grp_fu_456_ce;
reg    grp_fu_460_ce;
reg    grp_fu_464_ce;
reg    grp_fu_468_ce;
reg    grp_fu_472_ce;
reg    grp_fu_476_ce;
reg    grp_fu_480_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_1018;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_done_reg = 1'b0;
end

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_1351),
    .din1(32'd0),
    .ce(grp_fu_411_ce),
    .dout(grp_fu_411_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_reg_1371),
    .din1(mul92_s_reg_1356_pp0_iter7_reg),
    .ce(grp_fu_416_ce),
    .dout(grp_fu_416_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_1_reg_1376),
    .din1(mul92_3_reg_1366_pp0_iter11_reg),
    .ce(grp_fu_420_ce),
    .dout(grp_fu_420_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_2_reg_1391),
    .din1(mul92_1_reg_1396),
    .ce(grp_fu_424_ce),
    .dout(grp_fu_424_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_3_reg_1411),
    .din1(mul92_1_1_reg_1401_pp0_iter19_reg),
    .ce(grp_fu_428_ce),
    .dout(grp_fu_428_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_4_reg_1416),
    .din1(mul92_1_2_reg_1406_pp0_iter23_reg),
    .ce(grp_fu_432_ce),
    .dout(grp_fu_432_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_5_reg_1431),
    .din1(mul92_2_reg_1436),
    .ce(grp_fu_436_ce),
    .dout(grp_fu_436_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_6_reg_1451),
    .din1(mul92_2_1_reg_1441_pp0_iter31_reg),
    .ce(grp_fu_440_ce),
    .dout(grp_fu_440_p2)
);

conv2d_stream_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_7_reg_1456),
    .din1(mul92_2_2_reg_1446_pp0_iter35_reg),
    .ce(grp_fu_444_ce),
    .dout(grp_fu_444_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_448_p0),
    .din1(local_kernel_0_0214_reload),
    .ce(grp_fu_448_ce),
    .dout(grp_fu_448_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_452_p0),
    .din1(local_kernel_1_0215_reload),
    .ce(grp_fu_452_ce),
    .dout(grp_fu_452_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_0_2_reg_1321),
    .din1(local_kernel_2_0216_reload),
    .ce(grp_fu_456_ce),
    .dout(grp_fu_456_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_460_p0),
    .din1(local_kernel_3_0217_reload),
    .ce(grp_fu_460_ce),
    .dout(grp_fu_460_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_464_p0),
    .din1(local_kernel_4_0218_reload),
    .ce(grp_fu_464_ce),
    .dout(grp_fu_464_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(window_1_2_reg_1326_pp0_iter13_reg),
    .din1(local_kernel_5_0219_reload),
    .ce(grp_fu_468_ce),
    .dout(grp_fu_468_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_472_p0),
    .din1(local_kernel_6_0220_reload),
    .ce(grp_fu_472_ce),
    .dout(grp_fu_472_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_476_p0),
    .din1(local_kernel_7_0221_reload),
    .ce(grp_fu_476_ce),
    .dout(grp_fu_476_p2)
);

conv2d_stream_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(new_pixel_2_reg_398_pp0_iter25_reg),
    .din1(local_kernel_8_0222_reload),
    .ce(grp_fu_480_ce),
    .dout(grp_fu_480_p2)
);

conv2d_stream_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U37(
    .din0(add_ln66_1_reg_1254),
    .din1(cols),
    .dout(mul_ln66_fu_869_p2)
);

conv2d_stream_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1018)) begin
        if (((1'd0 == and_ln75_1_fu_788_p2) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_new_pixel_2_reg_398 <= 32'd0;
        end else if (((1'd1 == and_ln75_1_fu_788_p2) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_new_pixel_2_reg_398 <= new_pixel_fu_798_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_new_pixel_2_reg_398 <= ap_phi_reg_pp0_iter1_new_pixel_2_reg_398;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten13_fu_192 <= 64'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            indvar_flatten13_fu_192 <= add_ln66_fu_635_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pi_fu_188 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            pi_fu_188 <= select_ln66_4_fu_743_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pj_fu_160 <= 8'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            pj_fu_160 <= add_ln67_fu_848_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg39_fu_144 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            reuse_addr_reg39_fu_144 <= zext_ln67_fu_751_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            reuse_addr_reg_fu_152 <= 64'd18446744073709551615;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
            reuse_addr_reg_fu_152 <= zext_ln67_fu_751_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            reuse_reg38_fu_148 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            reuse_reg38_fu_148 <= window_1_2_fu_892_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            reuse_reg_fu_156 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            reuse_reg_fu_156 <= ap_phi_reg_pp0_iter2_new_pixel_2_reg_398;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_0_1_4_fu_164 <= window_0_1_1_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            window_0_1_4_fu_164 <= window_load_3_fu_925_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_0_1_fu_168 <= window_0_2_1_reload;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            window_0_1_fu_168 <= window_0_2_fu_882_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_1_1_4_fu_172 <= window_1_1_1_reload;
        end else if ((ap_enable_reg_pp0_iter14 == 1'b1)) begin
            window_1_1_4_fu_172 <= window_load_6_fu_1018_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_1_1_fu_176 <= window_1_2_1_reload;
        end else if ((ap_enable_reg_pp0_iter14 == 1'b1)) begin
            window_1_1_fu_176 <= window_1_2_reg_1326_pp0_iter13_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_2_1_4_fu_180 <= window_2_1_1_reload;
        end else if ((ap_enable_reg_pp0_iter26 == 1'b1)) begin
            window_2_1_4_fu_180 <= window_load_9_fu_1056_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            window_2_1_fu_184 <= window_2_2_1_reload;
        end else if ((ap_enable_reg_pp0_iter26 == 1'b1)) begin
            window_2_1_fu_184 <= new_pixel_2_reg_398_pp0_iter25_reg;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        acc_1_reg_1376 <= grp_fu_416_p2;
        acc_2_reg_1391 <= grp_fu_420_p2;
        acc_3_reg_1411 <= grp_fu_424_p2;
        acc_4_reg_1416 <= grp_fu_428_p2;
        acc_5_reg_1431 <= grp_fu_432_p2;
        acc_6_reg_1451 <= grp_fu_436_p2;
        acc_7_reg_1456 <= grp_fu_440_p2;
        acc_reg_1371 <= grp_fu_411_p2;
        and_ln124_1_reg_1342 <= and_ln124_1_fu_971_p2;
        and_ln124_1_reg_1342_pp0_iter10_reg <= and_ln124_1_reg_1342_pp0_iter9_reg;
        and_ln124_1_reg_1342_pp0_iter11_reg <= and_ln124_1_reg_1342_pp0_iter10_reg;
        and_ln124_1_reg_1342_pp0_iter12_reg <= and_ln124_1_reg_1342_pp0_iter11_reg;
        and_ln124_1_reg_1342_pp0_iter13_reg <= and_ln124_1_reg_1342_pp0_iter12_reg;
        and_ln124_1_reg_1342_pp0_iter14_reg <= and_ln124_1_reg_1342_pp0_iter13_reg;
        and_ln124_1_reg_1342_pp0_iter15_reg <= and_ln124_1_reg_1342_pp0_iter14_reg;
        and_ln124_1_reg_1342_pp0_iter16_reg <= and_ln124_1_reg_1342_pp0_iter15_reg;
        and_ln124_1_reg_1342_pp0_iter17_reg <= and_ln124_1_reg_1342_pp0_iter16_reg;
        and_ln124_1_reg_1342_pp0_iter18_reg <= and_ln124_1_reg_1342_pp0_iter17_reg;
        and_ln124_1_reg_1342_pp0_iter19_reg <= and_ln124_1_reg_1342_pp0_iter18_reg;
        and_ln124_1_reg_1342_pp0_iter20_reg <= and_ln124_1_reg_1342_pp0_iter19_reg;
        and_ln124_1_reg_1342_pp0_iter21_reg <= and_ln124_1_reg_1342_pp0_iter20_reg;
        and_ln124_1_reg_1342_pp0_iter22_reg <= and_ln124_1_reg_1342_pp0_iter21_reg;
        and_ln124_1_reg_1342_pp0_iter23_reg <= and_ln124_1_reg_1342_pp0_iter22_reg;
        and_ln124_1_reg_1342_pp0_iter24_reg <= and_ln124_1_reg_1342_pp0_iter23_reg;
        and_ln124_1_reg_1342_pp0_iter25_reg <= and_ln124_1_reg_1342_pp0_iter24_reg;
        and_ln124_1_reg_1342_pp0_iter26_reg <= and_ln124_1_reg_1342_pp0_iter25_reg;
        and_ln124_1_reg_1342_pp0_iter27_reg <= and_ln124_1_reg_1342_pp0_iter26_reg;
        and_ln124_1_reg_1342_pp0_iter28_reg <= and_ln124_1_reg_1342_pp0_iter27_reg;
        and_ln124_1_reg_1342_pp0_iter29_reg <= and_ln124_1_reg_1342_pp0_iter28_reg;
        and_ln124_1_reg_1342_pp0_iter30_reg <= and_ln124_1_reg_1342_pp0_iter29_reg;
        and_ln124_1_reg_1342_pp0_iter31_reg <= and_ln124_1_reg_1342_pp0_iter30_reg;
        and_ln124_1_reg_1342_pp0_iter32_reg <= and_ln124_1_reg_1342_pp0_iter31_reg;
        and_ln124_1_reg_1342_pp0_iter33_reg <= and_ln124_1_reg_1342_pp0_iter32_reg;
        and_ln124_1_reg_1342_pp0_iter34_reg <= and_ln124_1_reg_1342_pp0_iter33_reg;
        and_ln124_1_reg_1342_pp0_iter35_reg <= and_ln124_1_reg_1342_pp0_iter34_reg;
        and_ln124_1_reg_1342_pp0_iter36_reg <= and_ln124_1_reg_1342_pp0_iter35_reg;
        and_ln124_1_reg_1342_pp0_iter37_reg <= and_ln124_1_reg_1342_pp0_iter36_reg;
        and_ln124_1_reg_1342_pp0_iter38_reg <= and_ln124_1_reg_1342_pp0_iter37_reg;
        and_ln124_1_reg_1342_pp0_iter3_reg <= and_ln124_1_reg_1342;
        and_ln124_1_reg_1342_pp0_iter4_reg <= and_ln124_1_reg_1342_pp0_iter3_reg;
        and_ln124_1_reg_1342_pp0_iter5_reg <= and_ln124_1_reg_1342_pp0_iter4_reg;
        and_ln124_1_reg_1342_pp0_iter6_reg <= and_ln124_1_reg_1342_pp0_iter5_reg;
        and_ln124_1_reg_1342_pp0_iter7_reg <= and_ln124_1_reg_1342_pp0_iter6_reg;
        and_ln124_1_reg_1342_pp0_iter8_reg <= and_ln124_1_reg_1342_pp0_iter7_reg;
        and_ln124_1_reg_1342_pp0_iter9_reg <= and_ln124_1_reg_1342_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        empty_18_reg_1314_pp0_iter10_reg <= empty_18_reg_1314_pp0_iter9_reg;
        empty_18_reg_1314_pp0_iter11_reg <= empty_18_reg_1314_pp0_iter10_reg;
        empty_18_reg_1314_pp0_iter12_reg <= empty_18_reg_1314_pp0_iter11_reg;
        empty_18_reg_1314_pp0_iter13_reg <= empty_18_reg_1314_pp0_iter12_reg;
        empty_18_reg_1314_pp0_iter14_reg <= empty_18_reg_1314_pp0_iter13_reg;
        empty_18_reg_1314_pp0_iter15_reg <= empty_18_reg_1314_pp0_iter14_reg;
        empty_18_reg_1314_pp0_iter16_reg <= empty_18_reg_1314_pp0_iter15_reg;
        empty_18_reg_1314_pp0_iter17_reg <= empty_18_reg_1314_pp0_iter16_reg;
        empty_18_reg_1314_pp0_iter18_reg <= empty_18_reg_1314_pp0_iter17_reg;
        empty_18_reg_1314_pp0_iter19_reg <= empty_18_reg_1314_pp0_iter18_reg;
        empty_18_reg_1314_pp0_iter20_reg <= empty_18_reg_1314_pp0_iter19_reg;
        empty_18_reg_1314_pp0_iter21_reg <= empty_18_reg_1314_pp0_iter20_reg;
        empty_18_reg_1314_pp0_iter22_reg <= empty_18_reg_1314_pp0_iter21_reg;
        empty_18_reg_1314_pp0_iter23_reg <= empty_18_reg_1314_pp0_iter22_reg;
        empty_18_reg_1314_pp0_iter24_reg <= empty_18_reg_1314_pp0_iter23_reg;
        empty_18_reg_1314_pp0_iter25_reg <= empty_18_reg_1314_pp0_iter24_reg;
        empty_18_reg_1314_pp0_iter2_reg <= empty_18_reg_1314;
        empty_18_reg_1314_pp0_iter3_reg <= empty_18_reg_1314_pp0_iter2_reg;
        empty_18_reg_1314_pp0_iter4_reg <= empty_18_reg_1314_pp0_iter3_reg;
        empty_18_reg_1314_pp0_iter5_reg <= empty_18_reg_1314_pp0_iter4_reg;
        empty_18_reg_1314_pp0_iter6_reg <= empty_18_reg_1314_pp0_iter5_reg;
        empty_18_reg_1314_pp0_iter7_reg <= empty_18_reg_1314_pp0_iter6_reg;
        empty_18_reg_1314_pp0_iter8_reg <= empty_18_reg_1314_pp0_iter7_reg;
        empty_18_reg_1314_pp0_iter9_reg <= empty_18_reg_1314_pp0_iter8_reg;
        icmp_ln97_1_reg_1307_pp0_iter10_reg <= icmp_ln97_1_reg_1307_pp0_iter9_reg;
        icmp_ln97_1_reg_1307_pp0_iter11_reg <= icmp_ln97_1_reg_1307_pp0_iter10_reg;
        icmp_ln97_1_reg_1307_pp0_iter12_reg <= icmp_ln97_1_reg_1307_pp0_iter11_reg;
        icmp_ln97_1_reg_1307_pp0_iter13_reg <= icmp_ln97_1_reg_1307_pp0_iter12_reg;
        icmp_ln97_1_reg_1307_pp0_iter14_reg <= icmp_ln97_1_reg_1307_pp0_iter13_reg;
        icmp_ln97_1_reg_1307_pp0_iter15_reg <= icmp_ln97_1_reg_1307_pp0_iter14_reg;
        icmp_ln97_1_reg_1307_pp0_iter16_reg <= icmp_ln97_1_reg_1307_pp0_iter15_reg;
        icmp_ln97_1_reg_1307_pp0_iter17_reg <= icmp_ln97_1_reg_1307_pp0_iter16_reg;
        icmp_ln97_1_reg_1307_pp0_iter18_reg <= icmp_ln97_1_reg_1307_pp0_iter17_reg;
        icmp_ln97_1_reg_1307_pp0_iter19_reg <= icmp_ln97_1_reg_1307_pp0_iter18_reg;
        icmp_ln97_1_reg_1307_pp0_iter20_reg <= icmp_ln97_1_reg_1307_pp0_iter19_reg;
        icmp_ln97_1_reg_1307_pp0_iter21_reg <= icmp_ln97_1_reg_1307_pp0_iter20_reg;
        icmp_ln97_1_reg_1307_pp0_iter22_reg <= icmp_ln97_1_reg_1307_pp0_iter21_reg;
        icmp_ln97_1_reg_1307_pp0_iter23_reg <= icmp_ln97_1_reg_1307_pp0_iter22_reg;
        icmp_ln97_1_reg_1307_pp0_iter24_reg <= icmp_ln97_1_reg_1307_pp0_iter23_reg;
        icmp_ln97_1_reg_1307_pp0_iter25_reg <= icmp_ln97_1_reg_1307_pp0_iter24_reg;
        icmp_ln97_1_reg_1307_pp0_iter2_reg <= icmp_ln97_1_reg_1307;
        icmp_ln97_1_reg_1307_pp0_iter3_reg <= icmp_ln97_1_reg_1307_pp0_iter2_reg;
        icmp_ln97_1_reg_1307_pp0_iter4_reg <= icmp_ln97_1_reg_1307_pp0_iter3_reg;
        icmp_ln97_1_reg_1307_pp0_iter5_reg <= icmp_ln97_1_reg_1307_pp0_iter4_reg;
        icmp_ln97_1_reg_1307_pp0_iter6_reg <= icmp_ln97_1_reg_1307_pp0_iter5_reg;
        icmp_ln97_1_reg_1307_pp0_iter7_reg <= icmp_ln97_1_reg_1307_pp0_iter6_reg;
        icmp_ln97_1_reg_1307_pp0_iter8_reg <= icmp_ln97_1_reg_1307_pp0_iter7_reg;
        icmp_ln97_1_reg_1307_pp0_iter9_reg <= icmp_ln97_1_reg_1307_pp0_iter8_reg;
        icmp_ln97_reg_1300_pp0_iter10_reg <= icmp_ln97_reg_1300_pp0_iter9_reg;
        icmp_ln97_reg_1300_pp0_iter11_reg <= icmp_ln97_reg_1300_pp0_iter10_reg;
        icmp_ln97_reg_1300_pp0_iter12_reg <= icmp_ln97_reg_1300_pp0_iter11_reg;
        icmp_ln97_reg_1300_pp0_iter13_reg <= icmp_ln97_reg_1300_pp0_iter12_reg;
        icmp_ln97_reg_1300_pp0_iter14_reg <= icmp_ln97_reg_1300_pp0_iter13_reg;
        icmp_ln97_reg_1300_pp0_iter15_reg <= icmp_ln97_reg_1300_pp0_iter14_reg;
        icmp_ln97_reg_1300_pp0_iter16_reg <= icmp_ln97_reg_1300_pp0_iter15_reg;
        icmp_ln97_reg_1300_pp0_iter17_reg <= icmp_ln97_reg_1300_pp0_iter16_reg;
        icmp_ln97_reg_1300_pp0_iter18_reg <= icmp_ln97_reg_1300_pp0_iter17_reg;
        icmp_ln97_reg_1300_pp0_iter19_reg <= icmp_ln97_reg_1300_pp0_iter18_reg;
        icmp_ln97_reg_1300_pp0_iter20_reg <= icmp_ln97_reg_1300_pp0_iter19_reg;
        icmp_ln97_reg_1300_pp0_iter21_reg <= icmp_ln97_reg_1300_pp0_iter20_reg;
        icmp_ln97_reg_1300_pp0_iter22_reg <= icmp_ln97_reg_1300_pp0_iter21_reg;
        icmp_ln97_reg_1300_pp0_iter23_reg <= icmp_ln97_reg_1300_pp0_iter22_reg;
        icmp_ln97_reg_1300_pp0_iter24_reg <= icmp_ln97_reg_1300_pp0_iter23_reg;
        icmp_ln97_reg_1300_pp0_iter25_reg <= icmp_ln97_reg_1300_pp0_iter24_reg;
        icmp_ln97_reg_1300_pp0_iter2_reg <= icmp_ln97_reg_1300;
        icmp_ln97_reg_1300_pp0_iter3_reg <= icmp_ln97_reg_1300_pp0_iter2_reg;
        icmp_ln97_reg_1300_pp0_iter4_reg <= icmp_ln97_reg_1300_pp0_iter3_reg;
        icmp_ln97_reg_1300_pp0_iter5_reg <= icmp_ln97_reg_1300_pp0_iter4_reg;
        icmp_ln97_reg_1300_pp0_iter6_reg <= icmp_ln97_reg_1300_pp0_iter5_reg;
        icmp_ln97_reg_1300_pp0_iter7_reg <= icmp_ln97_reg_1300_pp0_iter6_reg;
        icmp_ln97_reg_1300_pp0_iter8_reg <= icmp_ln97_reg_1300_pp0_iter7_reg;
        icmp_ln97_reg_1300_pp0_iter9_reg <= icmp_ln97_reg_1300_pp0_iter8_reg;
        is_last_reg_1361_pp0_iter10_reg <= is_last_reg_1361_pp0_iter9_reg;
        is_last_reg_1361_pp0_iter11_reg <= is_last_reg_1361_pp0_iter10_reg;
        is_last_reg_1361_pp0_iter12_reg <= is_last_reg_1361_pp0_iter11_reg;
        is_last_reg_1361_pp0_iter13_reg <= is_last_reg_1361_pp0_iter12_reg;
        is_last_reg_1361_pp0_iter14_reg <= is_last_reg_1361_pp0_iter13_reg;
        is_last_reg_1361_pp0_iter15_reg <= is_last_reg_1361_pp0_iter14_reg;
        is_last_reg_1361_pp0_iter16_reg <= is_last_reg_1361_pp0_iter15_reg;
        is_last_reg_1361_pp0_iter17_reg <= is_last_reg_1361_pp0_iter16_reg;
        is_last_reg_1361_pp0_iter18_reg <= is_last_reg_1361_pp0_iter17_reg;
        is_last_reg_1361_pp0_iter19_reg <= is_last_reg_1361_pp0_iter18_reg;
        is_last_reg_1361_pp0_iter20_reg <= is_last_reg_1361_pp0_iter19_reg;
        is_last_reg_1361_pp0_iter21_reg <= is_last_reg_1361_pp0_iter20_reg;
        is_last_reg_1361_pp0_iter22_reg <= is_last_reg_1361_pp0_iter21_reg;
        is_last_reg_1361_pp0_iter23_reg <= is_last_reg_1361_pp0_iter22_reg;
        is_last_reg_1361_pp0_iter24_reg <= is_last_reg_1361_pp0_iter23_reg;
        is_last_reg_1361_pp0_iter25_reg <= is_last_reg_1361_pp0_iter24_reg;
        is_last_reg_1361_pp0_iter26_reg <= is_last_reg_1361_pp0_iter25_reg;
        is_last_reg_1361_pp0_iter27_reg <= is_last_reg_1361_pp0_iter26_reg;
        is_last_reg_1361_pp0_iter28_reg <= is_last_reg_1361_pp0_iter27_reg;
        is_last_reg_1361_pp0_iter29_reg <= is_last_reg_1361_pp0_iter28_reg;
        is_last_reg_1361_pp0_iter30_reg <= is_last_reg_1361_pp0_iter29_reg;
        is_last_reg_1361_pp0_iter31_reg <= is_last_reg_1361_pp0_iter30_reg;
        is_last_reg_1361_pp0_iter32_reg <= is_last_reg_1361_pp0_iter31_reg;
        is_last_reg_1361_pp0_iter33_reg <= is_last_reg_1361_pp0_iter32_reg;
        is_last_reg_1361_pp0_iter34_reg <= is_last_reg_1361_pp0_iter33_reg;
        is_last_reg_1361_pp0_iter35_reg <= is_last_reg_1361_pp0_iter34_reg;
        is_last_reg_1361_pp0_iter36_reg <= is_last_reg_1361_pp0_iter35_reg;
        is_last_reg_1361_pp0_iter37_reg <= is_last_reg_1361_pp0_iter36_reg;
        is_last_reg_1361_pp0_iter38_reg <= is_last_reg_1361_pp0_iter37_reg;
        is_last_reg_1361_pp0_iter4_reg <= is_last_reg_1361;
        is_last_reg_1361_pp0_iter5_reg <= is_last_reg_1361_pp0_iter4_reg;
        is_last_reg_1361_pp0_iter6_reg <= is_last_reg_1361_pp0_iter5_reg;
        is_last_reg_1361_pp0_iter7_reg <= is_last_reg_1361_pp0_iter6_reg;
        is_last_reg_1361_pp0_iter8_reg <= is_last_reg_1361_pp0_iter7_reg;
        is_last_reg_1361_pp0_iter9_reg <= is_last_reg_1361_pp0_iter8_reg;
        mul92_1_1_reg_1401 <= grp_fu_464_p2;
        mul92_1_1_reg_1401_pp0_iter16_reg <= mul92_1_1_reg_1401;
        mul92_1_1_reg_1401_pp0_iter17_reg <= mul92_1_1_reg_1401_pp0_iter16_reg;
        mul92_1_1_reg_1401_pp0_iter18_reg <= mul92_1_1_reg_1401_pp0_iter17_reg;
        mul92_1_1_reg_1401_pp0_iter19_reg <= mul92_1_1_reg_1401_pp0_iter18_reg;
        mul92_1_2_reg_1406 <= grp_fu_468_p2;
        mul92_1_2_reg_1406_pp0_iter16_reg <= mul92_1_2_reg_1406;
        mul92_1_2_reg_1406_pp0_iter17_reg <= mul92_1_2_reg_1406_pp0_iter16_reg;
        mul92_1_2_reg_1406_pp0_iter18_reg <= mul92_1_2_reg_1406_pp0_iter17_reg;
        mul92_1_2_reg_1406_pp0_iter19_reg <= mul92_1_2_reg_1406_pp0_iter18_reg;
        mul92_1_2_reg_1406_pp0_iter20_reg <= mul92_1_2_reg_1406_pp0_iter19_reg;
        mul92_1_2_reg_1406_pp0_iter21_reg <= mul92_1_2_reg_1406_pp0_iter20_reg;
        mul92_1_2_reg_1406_pp0_iter22_reg <= mul92_1_2_reg_1406_pp0_iter21_reg;
        mul92_1_2_reg_1406_pp0_iter23_reg <= mul92_1_2_reg_1406_pp0_iter22_reg;
        mul92_1_reg_1396 <= grp_fu_460_p2;
        mul92_2_1_reg_1441 <= grp_fu_476_p2;
        mul92_2_1_reg_1441_pp0_iter28_reg <= mul92_2_1_reg_1441;
        mul92_2_1_reg_1441_pp0_iter29_reg <= mul92_2_1_reg_1441_pp0_iter28_reg;
        mul92_2_1_reg_1441_pp0_iter30_reg <= mul92_2_1_reg_1441_pp0_iter29_reg;
        mul92_2_1_reg_1441_pp0_iter31_reg <= mul92_2_1_reg_1441_pp0_iter30_reg;
        mul92_2_2_reg_1446 <= grp_fu_480_p2;
        mul92_2_2_reg_1446_pp0_iter28_reg <= mul92_2_2_reg_1446;
        mul92_2_2_reg_1446_pp0_iter29_reg <= mul92_2_2_reg_1446_pp0_iter28_reg;
        mul92_2_2_reg_1446_pp0_iter30_reg <= mul92_2_2_reg_1446_pp0_iter29_reg;
        mul92_2_2_reg_1446_pp0_iter31_reg <= mul92_2_2_reg_1446_pp0_iter30_reg;
        mul92_2_2_reg_1446_pp0_iter32_reg <= mul92_2_2_reg_1446_pp0_iter31_reg;
        mul92_2_2_reg_1446_pp0_iter33_reg <= mul92_2_2_reg_1446_pp0_iter32_reg;
        mul92_2_2_reg_1446_pp0_iter34_reg <= mul92_2_2_reg_1446_pp0_iter33_reg;
        mul92_2_2_reg_1446_pp0_iter35_reg <= mul92_2_2_reg_1446_pp0_iter34_reg;
        mul92_2_reg_1436 <= grp_fu_472_p2;
        mul92_3_reg_1366 <= grp_fu_456_p2;
        mul92_3_reg_1366_pp0_iter10_reg <= mul92_3_reg_1366_pp0_iter9_reg;
        mul92_3_reg_1366_pp0_iter11_reg <= mul92_3_reg_1366_pp0_iter10_reg;
        mul92_3_reg_1366_pp0_iter5_reg <= mul92_3_reg_1366;
        mul92_3_reg_1366_pp0_iter6_reg <= mul92_3_reg_1366_pp0_iter5_reg;
        mul92_3_reg_1366_pp0_iter7_reg <= mul92_3_reg_1366_pp0_iter6_reg;
        mul92_3_reg_1366_pp0_iter8_reg <= mul92_3_reg_1366_pp0_iter7_reg;
        mul92_3_reg_1366_pp0_iter9_reg <= mul92_3_reg_1366_pp0_iter8_reg;
        mul92_s_reg_1356 <= grp_fu_452_p2;
        mul92_s_reg_1356_pp0_iter4_reg <= mul92_s_reg_1356;
        mul92_s_reg_1356_pp0_iter5_reg <= mul92_s_reg_1356_pp0_iter4_reg;
        mul92_s_reg_1356_pp0_iter6_reg <= mul92_s_reg_1356_pp0_iter5_reg;
        mul92_s_reg_1356_pp0_iter7_reg <= mul92_s_reg_1356_pp0_iter6_reg;
        mul_reg_1351 <= grp_fu_448_p2;
        new_pixel_2_reg_398_pp0_iter10_reg <= new_pixel_2_reg_398_pp0_iter9_reg;
        new_pixel_2_reg_398_pp0_iter11_reg <= new_pixel_2_reg_398_pp0_iter10_reg;
        new_pixel_2_reg_398_pp0_iter12_reg <= new_pixel_2_reg_398_pp0_iter11_reg;
        new_pixel_2_reg_398_pp0_iter13_reg <= new_pixel_2_reg_398_pp0_iter12_reg;
        new_pixel_2_reg_398_pp0_iter14_reg <= new_pixel_2_reg_398_pp0_iter13_reg;
        new_pixel_2_reg_398_pp0_iter15_reg <= new_pixel_2_reg_398_pp0_iter14_reg;
        new_pixel_2_reg_398_pp0_iter16_reg <= new_pixel_2_reg_398_pp0_iter15_reg;
        new_pixel_2_reg_398_pp0_iter17_reg <= new_pixel_2_reg_398_pp0_iter16_reg;
        new_pixel_2_reg_398_pp0_iter18_reg <= new_pixel_2_reg_398_pp0_iter17_reg;
        new_pixel_2_reg_398_pp0_iter19_reg <= new_pixel_2_reg_398_pp0_iter18_reg;
        new_pixel_2_reg_398_pp0_iter20_reg <= new_pixel_2_reg_398_pp0_iter19_reg;
        new_pixel_2_reg_398_pp0_iter21_reg <= new_pixel_2_reg_398_pp0_iter20_reg;
        new_pixel_2_reg_398_pp0_iter22_reg <= new_pixel_2_reg_398_pp0_iter21_reg;
        new_pixel_2_reg_398_pp0_iter23_reg <= new_pixel_2_reg_398_pp0_iter22_reg;
        new_pixel_2_reg_398_pp0_iter24_reg <= new_pixel_2_reg_398_pp0_iter23_reg;
        new_pixel_2_reg_398_pp0_iter25_reg <= new_pixel_2_reg_398_pp0_iter24_reg;
        new_pixel_2_reg_398_pp0_iter3_reg <= new_pixel_2_reg_398;
        new_pixel_2_reg_398_pp0_iter4_reg <= new_pixel_2_reg_398_pp0_iter3_reg;
        new_pixel_2_reg_398_pp0_iter5_reg <= new_pixel_2_reg_398_pp0_iter4_reg;
        new_pixel_2_reg_398_pp0_iter6_reg <= new_pixel_2_reg_398_pp0_iter5_reg;
        new_pixel_2_reg_398_pp0_iter7_reg <= new_pixel_2_reg_398_pp0_iter6_reg;
        new_pixel_2_reg_398_pp0_iter8_reg <= new_pixel_2_reg_398_pp0_iter7_reg;
        new_pixel_2_reg_398_pp0_iter9_reg <= new_pixel_2_reg_398_pp0_iter8_reg;
        window_0_2_reg_1321 <= window_0_2_fu_882_p3;
        window_1_2_reg_1326 <= window_1_2_fu_892_p3;
        window_1_2_reg_1326_pp0_iter10_reg <= window_1_2_reg_1326_pp0_iter9_reg;
        window_1_2_reg_1326_pp0_iter11_reg <= window_1_2_reg_1326_pp0_iter10_reg;
        window_1_2_reg_1326_pp0_iter12_reg <= window_1_2_reg_1326_pp0_iter11_reg;
        window_1_2_reg_1326_pp0_iter13_reg <= window_1_2_reg_1326_pp0_iter12_reg;
        window_1_2_reg_1326_pp0_iter3_reg <= window_1_2_reg_1326;
        window_1_2_reg_1326_pp0_iter4_reg <= window_1_2_reg_1326_pp0_iter3_reg;
        window_1_2_reg_1326_pp0_iter5_reg <= window_1_2_reg_1326_pp0_iter4_reg;
        window_1_2_reg_1326_pp0_iter6_reg <= window_1_2_reg_1326_pp0_iter5_reg;
        window_1_2_reg_1326_pp0_iter7_reg <= window_1_2_reg_1326_pp0_iter6_reg;
        window_1_2_reg_1326_pp0_iter8_reg <= window_1_2_reg_1326_pp0_iter7_reg;
        window_1_2_reg_1326_pp0_iter9_reg <= window_1_2_reg_1326_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln124_1_fu_971_p2))) begin
        add_ln129_reg_1346 <= add_ln129_fu_977_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln66_fu_630_p2 == 1'd0))) begin
        add_ln66_1_reg_1254 <= add_ln66_1_fu_679_p2;
        addr_cmp42_reg_1284 <= addr_cmp42_fu_805_p2;
        addr_cmp_reg_1295 <= addr_cmp_fu_814_p2;
        empty_18_reg_1314 <= empty_18_fu_842_p2;
        icmp_ln97_1_reg_1307 <= icmp_ln97_1_fu_836_p2;
        icmp_ln97_reg_1300 <= icmp_ln97_fu_830_p2;
        line_buf_0_addr_reg_1278 <= zext_ln67_fu_751_p1;
        line_buf_1_addr_reg_1289 <= zext_ln67_fu_751_p1;
        select_ln66_3_reg_1259 <= select_ln66_3_fu_735_p3;
        select_ln66_reg_1249 <= select_ln66_fu_641_p3;
        zext_ln67_1_reg_1264[7 : 0] <= zext_ln67_1_fu_757_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        sext_ln66_cast_reg_1237 <= sext_ln66_cast_fu_485_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_new_pixel_2_reg_398 <= ap_phi_reg_pp0_iter0_new_pixel_2_reg_398;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln124_1_reg_1342))) begin
        is_last_reg_1361 <= is_last_fu_993_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        new_pixel_2_reg_398 <= ap_phi_reg_pp0_iter2_new_pixel_2_reg_398;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln66_fu_630_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter38_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_411_ce = 1'b1;
    end else begin
        grp_fu_411_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_416_ce = 1'b1;
    end else begin
        grp_fu_416_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_420_ce = 1'b1;
    end else begin
        grp_fu_420_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_424_ce = 1'b1;
    end else begin
        grp_fu_424_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_428_ce = 1'b1;
    end else begin
        grp_fu_428_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_432_ce = 1'b1;
    end else begin
        grp_fu_432_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_436_ce = 1'b1;
    end else begin
        grp_fu_436_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_440_ce = 1'b1;
    end else begin
        grp_fu_440_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_444_ce = 1'b1;
    end else begin
        grp_fu_444_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_448_ce = 1'b1;
    end else begin
        grp_fu_448_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_452_ce = 1'b1;
    end else begin
        grp_fu_452_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_456_ce = 1'b1;
    end else begin
        grp_fu_456_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_460_ce = 1'b1;
    end else begin
        grp_fu_460_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_464_ce = 1'b1;
    end else begin
        grp_fu_464_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_468_ce = 1'b1;
    end else begin
        grp_fu_468_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_472_ce = 1'b1;
    end else begin
        grp_fu_472_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_476_ce = 1'b1;
    end else begin
        grp_fu_476_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_480_ce = 1'b1;
    end else begin
        grp_fu_480_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op136_read_state2 == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op136_read_state2 == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_0_ce0 = 1'b1;
    end else begin
        line_buf_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_0_ce1 = 1'b1;
    end else begin
        line_buf_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_0_we0 = 1'b1;
    end else begin
        line_buf_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_1_ce0 = 1'b1;
    end else begin
        line_buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce1 = 1'b1;
    end else begin
        line_buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        line_buf_1_we0 = 1'b1;
    end else begin
        line_buf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        out_stream_TVALID = 1'b1;
    end else begin
        out_stream_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_fu_933_p2 = ($signed(zext_ln67_1_reg_1264) + $signed(9'd510));

assign add_ln125_fu_942_p2 = ($signed(select_ln66_reg_1249) + $signed(8'd254));

assign add_ln129_fu_977_p2 = ($signed(sext_ln125_fu_938_p1) + $signed(mul_ln66_fu_869_p2));

assign add_ln66_1_fu_679_p2 = (pi_fu_188 + select_ln66_1_fu_671_p3);

assign add_ln66_2_fu_649_p2 = (pi_fu_188 + 32'd1);

assign add_ln66_fu_635_p2 = (indvar_flatten13_fu_192 + 64'd1);

assign add_ln67_fu_848_p2 = (select_ln66_fu_641_p3 + 8'd1);

assign add_ln72_fu_761_p2 = ($signed(zext_ln67_1_fu_757_p1) + $signed(9'd511));

assign addr_cmp42_fu_805_p2 = ((reuse_addr_reg39_fu_144 == zext_ln67_fu_751_p1) ? 1'b1 : 1'b0);

assign addr_cmp_fu_814_p2 = ((reuse_addr_reg_fu_152 == zext_ln67_fu_751_p1) ? 1'b1 : 1'b0);

assign and_ln124_1_fu_971_p2 = (icmp_ln125_fu_961_p2 & and_ln124_2_fu_966_p2);

assign and_ln124_2_fu_966_p2 = (xor_ln125_fu_955_p2 & select_ln66_3_reg_1259);

assign and_ln124_3_fu_729_p2 = (rev37_fu_704_p2 & notrhs2_mid1_fu_710_p2);

assign and_ln124_fu_615_p2 = (rev_fu_598_p2 & notrhs2_fu_604_p2);

assign and_ln75_1_fu_788_p2 = (select_ln66_2_fu_721_p3 & and_ln75_2_fu_782_p2);

assign and_ln75_2_fu_782_p2 = (icmp_ln76_fu_771_p2 & icmp_ln76_1_fu_777_p2);

assign and_ln75_3_fu_715_p2 = (notrhs_mid1_fu_691_p2 & notlhs_mid1_fu_685_p2);

assign and_ln75_fu_609_p2 = (notrhs_fu_585_p2 & notlhs_fu_579_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_stream_TREADY == 1'b0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg) & (ap_enable_reg_pp0_iter39 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op136_read_state2 == 1'b1) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter39 == 1'b1) & ((1'b1 == ap_block_state40_io) | ((out_stream_TREADY == 1'b0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op136_read_state2 == 1'b1) & (in_stream_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter39 == 1'b1) & ((1'b1 == ap_block_state40_io) | ((out_stream_TREADY == 1'b0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op136_read_state2 == 1'b1) & (in_stream_TVALID == 1'b0)));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op136_read_state2 == 1'b1) & (in_stream_TVALID == 1'b0));
end

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state40_io = ((out_stream_TREADY == 1'b0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg));
end

always @ (*) begin
    ap_block_state40_pp0_stage0_iter39 = ((out_stream_TREADY == 1'b0) & (1'd1 == and_ln124_1_reg_1342_pp0_iter38_reg));
end

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1018 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_phi_reg_pp0_iter0_new_pixel_2_reg_398 = 'bx;

always @ (*) begin
    ap_predicate_op136_read_state2 = ((1'd1 == and_ln75_1_fu_788_p2) & (icmp_ln66_fu_630_p2 == 1'd0));
end

assign empty_17_fu_573_p2 = ($signed(zext_ln66_fu_563_p1) + $signed(33'd8589934590));

assign empty_18_fu_842_p2 = (icmp_ln97_fu_830_p2 | icmp_ln97_1_fu_836_p2);

assign empty_fu_567_p2 = ($signed(zext_ln66_fu_563_p1) + $signed(33'd8589934591));

assign grp_fu_448_p0 = ((empty_18_reg_1314[0:0] == 1'b1) ? 32'd0 : window_0_1_4_fu_164);

assign grp_fu_452_p0 = ((icmp_ln97_1_reg_1307[0:0] == 1'b1) ? window_0_1_fu_168 : select_ln97_fu_918_p3);

assign grp_fu_460_p0 = ((empty_18_reg_1314_pp0_iter13_reg[0:0] == 1'b1) ? 32'd0 : window_1_1_4_fu_172);

assign grp_fu_464_p0 = ((icmp_ln97_1_reg_1307_pp0_iter13_reg[0:0] == 1'b1) ? window_1_1_fu_176 : select_ln97_1_fu_1011_p3);

assign grp_fu_472_p0 = ((empty_18_reg_1314_pp0_iter25_reg[0:0] == 1'b1) ? 32'd0 : window_2_1_4_fu_180);

assign grp_fu_476_p0 = ((icmp_ln97_1_reg_1307_pp0_iter25_reg[0:0] == 1'b1) ? window_2_1_fu_184 : select_ln97_2_fu_1049_p3);

assign icmp_ln125_fu_961_p1 = cols;

assign icmp_ln125_fu_961_p2 = (($signed(sext_ln125_fu_938_p1) < $signed(icmp_ln125_fu_961_p1)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_630_p2 = ((indvar_flatten13_fu_192 == mul_ln39) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_625_p2 = ((zext_ln67_2_fu_621_p1 == padded_cols) ? 1'b1 : 1'b0);

assign icmp_ln76_1_fu_777_p1 = cols;

assign icmp_ln76_1_fu_777_p2 = (($signed(sext_ln76_fu_767_p1) < $signed(icmp_ln76_1_fu_777_p1)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_771_p2 = ((select_ln66_fu_641_p3 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln97_1_fu_836_p2 = ((select_ln66_fu_641_p3 == 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_830_p2 = ((select_ln66_fu_641_p3 == 8'd0) ? 1'b1 : 1'b0);

assign is_last_fu_993_p2 = ((add_ln129_reg_1346 == sub105) ? 1'b1 : 1'b0);

assign line_buf_0_address0 = line_buf_0_addr_reg_1278;

assign line_buf_0_address1 = zext_ln67_fu_751_p1;

assign line_buf_0_d0 = ((addr_cmp_reg_1295[0:0] == 1'b1) ? reuse_reg_fu_156 : line_buf_1_q1);

assign line_buf_1_address0 = line_buf_1_addr_reg_1289;

assign line_buf_1_address1 = zext_ln67_fu_751_p1;

assign line_buf_1_d0 = ap_phi_reg_pp0_iter2_new_pixel_2_reg_398;

assign new_pixel_fu_798_p1 = in_stream_TDATA;

assign notlhs_fu_579_p2 = ((pi_fu_188 != 32'd0) ? 1'b1 : 1'b0);

assign notlhs_mid1_fu_685_p2 = ((add_ln66_2_fu_649_p2 != 32'd0) ? 1'b1 : 1'b0);

assign notrhs2_fu_604_p2 = (($signed(empty_17_fu_573_p2) < $signed(sext_ln66_cast_reg_1237)) ? 1'b1 : 1'b0);

assign notrhs2_mid1_fu_710_p2 = (($signed(p_mid19_fu_665_p2) < $signed(sext_ln66_cast_reg_1237)) ? 1'b1 : 1'b0);

assign notrhs_fu_585_p2 = (($signed(empty_fu_567_p2) < $signed(sext_ln66_cast_reg_1237)) ? 1'b1 : 1'b0);

assign notrhs_mid1_fu_691_p2 = (($signed(p_mid1_fu_659_p2) < $signed(sext_ln66_cast_reg_1237)) ? 1'b1 : 1'b0);

assign out_stream_TDATA = grp_fu_444_p2;

assign out_stream_TDEST = 1'd0;

assign out_stream_TID = 1'd0;

assign out_stream_TKEEP = 4'd15;

assign out_stream_TLAST = is_last_reg_1361_pp0_iter38_reg;

assign out_stream_TSTRB = 4'd0;

assign out_stream_TUSER = 1'd0;

assign p_mid19_fu_665_p2 = ($signed(zext_ln66_1_fu_655_p1) + $signed(33'd8589934590));

assign p_mid1_fu_659_p2 = ($signed(zext_ln66_1_fu_655_p1) + $signed(33'd8589934591));

assign rev37_fu_704_p2 = (tmp_1_fu_696_p3 ^ 1'd1);

assign rev_fu_598_p2 = (tmp_fu_590_p3 ^ 1'd1);

assign select_ln66_1_fu_671_p3 = ((icmp_ln67_fu_625_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd4294967294);

assign select_ln66_2_fu_721_p3 = ((icmp_ln67_fu_625_p2[0:0] == 1'b1) ? and_ln75_3_fu_715_p2 : and_ln75_fu_609_p2);

assign select_ln66_3_fu_735_p3 = ((icmp_ln67_fu_625_p2[0:0] == 1'b1) ? and_ln124_3_fu_729_p2 : and_ln124_fu_615_p2);

assign select_ln66_4_fu_743_p3 = ((icmp_ln67_fu_625_p2[0:0] == 1'b1) ? add_ln66_2_fu_649_p2 : pi_fu_188);

assign select_ln66_fu_641_p3 = ((icmp_ln67_fu_625_p2[0:0] == 1'b1) ? 8'd0 : pj_fu_160);

assign select_ln97_1_fu_1011_p3 = ((icmp_ln97_reg_1300_pp0_iter13_reg[0:0] == 1'b1) ? 32'd0 : window_1_1_fu_176);

assign select_ln97_2_fu_1049_p3 = ((icmp_ln97_reg_1300_pp0_iter25_reg[0:0] == 1'b1) ? 32'd0 : window_2_1_fu_184);

assign select_ln97_fu_918_p3 = ((icmp_ln97_reg_1300[0:0] == 1'b1) ? 32'd0 : window_0_1_fu_168);

assign sext_ln125_fu_938_p1 = $signed(add_ln123_fu_933_p2);

assign sext_ln66_cast_fu_485_p1 = $signed(sext_ln66);

assign sext_ln76_fu_767_p1 = $signed(add_ln72_fu_761_p2);

assign tmp_1_fu_696_p3 = p_mid19_fu_665_p2[32'd32];

assign tmp_3_fu_947_p3 = add_ln125_fu_942_p2[32'd7];

assign tmp_fu_590_p3 = empty_17_fu_573_p2[32'd32];

assign window_0_2_fu_882_p3 = ((addr_cmp42_reg_1284[0:0] == 1'b1) ? reuse_reg38_fu_148 : line_buf_0_q1);

assign window_1_2_fu_892_p3 = ((addr_cmp_reg_1295[0:0] == 1'b1) ? reuse_reg_fu_156 : line_buf_1_q1);

assign window_load_3_fu_925_p3 = ((icmp_ln97_1_reg_1307[0:0] == 1'b1) ? window_0_1_fu_168 : select_ln97_fu_918_p3);

assign window_load_6_fu_1018_p3 = ((icmp_ln97_1_reg_1307_pp0_iter13_reg[0:0] == 1'b1) ? window_1_1_fu_176 : select_ln97_1_fu_1011_p3);

assign window_load_9_fu_1056_p3 = ((icmp_ln97_1_reg_1307_pp0_iter25_reg[0:0] == 1'b1) ? window_2_1_fu_184 : select_ln97_2_fu_1049_p3);

assign xor_ln125_fu_955_p2 = (tmp_3_fu_947_p3 ^ 1'd1);

assign zext_ln66_1_fu_655_p1 = add_ln66_2_fu_649_p2;

assign zext_ln66_fu_563_p1 = pi_fu_188;

assign zext_ln67_1_fu_757_p1 = select_ln66_fu_641_p3;

assign zext_ln67_2_fu_621_p1 = pj_fu_160;

assign zext_ln67_fu_751_p1 = select_ln66_fu_641_p3;

always @ (posedge ap_clk) begin
    zext_ln67_1_reg_1264[8] <= 1'b0;
end

endmodule //conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_66_5_VITIS_LOOP_67_6
