-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d_stream is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 7;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_local_block : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of conv2d_stream is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d_stream_conv2d_stream,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=200.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=152.447250,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=2089,HLS_SYN_LUT=3220,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_2 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_local_deadlock : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal rows : STD_LOGIC_VECTOR (31 downto 0);
    signal cols : STD_LOGIC_VECTOR (31 downto 0);
    signal kernel_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_read_reg_510 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_read_reg_517 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln30_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_reg_629 : STD_LOGIC_VECTOR (0 downto 0);
    signal padded_cols_fu_427_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_cols_reg_633 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln50_fu_432_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln50_reg_639 : STD_LOGIC_VECTOR (30 downto 0);
    signal sub105_fu_444_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub105_reg_644 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln52_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_649 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal local_kernel_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_load_reg_658 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal window_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_reg_673 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_load_1_reg_678 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal local_kernel_load_2_reg_683 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_1_reg_698 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_2_reg_703 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_load_3_reg_708 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal local_kernel_load_4_reg_713 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_3_reg_728 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_4_reg_733 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_load_5_reg_738 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal local_kernel_load_6_reg_743 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_5_reg_758 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_6_reg_763 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound4_fu_468_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal bound4_reg_768 : STD_LOGIC_VECTOR (62 downto 0);
    signal local_kernel_load_7_reg_773 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal local_kernel_load_8_reg_778 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_7_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_load_8_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal local_kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal local_kernel_ce0 : STD_LOGIC;
    signal local_kernel_we0 : STD_LOGIC;
    signal local_kernel_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal local_kernel_ce1 : STD_LOGIC;
    signal line_buf_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_ce0 : STD_LOGIC;
    signal line_buf_we0 : STD_LOGIC;
    signal line_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal line_buf_ce1 : STD_LOGIC;
    signal line_buf_we1 : STD_LOGIC;
    signal line_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal line_buf_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal window_ce0 : STD_LOGIC;
    signal window_we0 : STD_LOGIC;
    signal window_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal window_ce1 : STD_LOGIC;
    signal window_we1 : STD_LOGIC;
    signal window_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_idle : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_ready : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we0 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we1 : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_in_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TREADY : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out_ap_vld : STD_LOGIC;
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg : STD_LOGIC := '0';
    signal grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln30_fu_421_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul104_fu_440_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal padded_rows_fu_435_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln52_1_fu_456_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal bound4_fu_468_p0 : STD_LOGIC_VECTOR (30 downto 0);
    signal bound4_fu_468_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal bound4_fu_468_p00 : STD_LOGIC_VECTOR (62 downto 0);
    signal bound4_fu_468_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_33_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : OUT STD_LOGIC;
        kernel_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        local_kernel_ce0 : OUT STD_LOGIC;
        local_kernel_we0 : OUT STD_LOGIC;
        local_kernel_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_42_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        line_buf_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf_ce0 : OUT STD_LOGIC;
        line_buf_we0 : OUT STD_LOGIC;
        line_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf_ce1 : OUT STD_LOGIC;
        line_buf_we1 : OUT STD_LOGIC;
        line_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        window_ce0 : OUT STD_LOGIC;
        window_we0 : OUT STD_LOGIC;
        window_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        window_load_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        window_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        padded_cols : IN STD_LOGIC_VECTOR (31 downto 0);
        bound4 : IN STD_LOGIC_VECTOR (62 downto 0);
        local_kernel_load : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        local_kernel_load_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        line_buf_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf_ce0 : OUT STD_LOGIC;
        line_buf_we0 : OUT STD_LOGIC;
        line_buf_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        line_buf_address1 : OUT STD_LOGIC_VECTOR (8 downto 0);
        line_buf_ce1 : OUT STD_LOGIC;
        line_buf_we1 : OUT STD_LOGIC;
        line_buf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        line_buf_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        sub105 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_phi_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_phi_out_ap_vld : OUT STD_LOGIC;
        p_phi9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_phi9_out_ap_vld : OUT STD_LOGIC;
        p_phi10_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        p_phi10_out_ap_vld : OUT STD_LOGIC );
    end component;


    component conv2d_stream_mul_32s_32s_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_mul_31ns_32ns_63_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (30 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component conv2d_stream_local_kernel_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_line_buf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_window_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv2d_stream_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        rows : OUT STD_LOGIC_VECTOR (31 downto 0);
        cols : OUT STD_LOGIC_VECTOR (31 downto 0);
        kernel_address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        kernel_ce0 : IN STD_LOGIC;
        kernel_q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        ap_local_deadlock : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv2d_stream_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    local_kernel_U : component conv2d_stream_local_kernel_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => local_kernel_address0,
        ce0 => local_kernel_ce0,
        we0 => local_kernel_we0,
        d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_d0,
        q0 => local_kernel_q0,
        address1 => local_kernel_address1,
        ce1 => local_kernel_ce1,
        q1 => local_kernel_q1);

    line_buf_U : component conv2d_stream_line_buf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 260,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => line_buf_address0,
        ce0 => line_buf_ce0,
        we0 => line_buf_we0,
        d0 => line_buf_d0,
        q0 => line_buf_q0,
        address1 => line_buf_address1,
        ce1 => line_buf_ce1,
        we1 => line_buf_we1,
        d1 => line_buf_d1,
        q1 => line_buf_q1);

    window_U : component conv2d_stream_window_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => window_address0,
        ce0 => window_ce0,
        we0 => window_we0,
        d0 => window_d0,
        q0 => window_q0,
        address1 => window_address1,
        ce1 => window_ce1,
        we1 => window_we1,
        d1 => window_d1,
        q1 => window_q1);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_33_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_ready,
        kernel_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_address0,
        kernel_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_ce0,
        kernel_q0 => kernel_q0,
        local_kernel_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_address0,
        local_kernel_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_ce0,
        local_kernel_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_we0,
        local_kernel_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_d0);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_42_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_ready,
        line_buf_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address0,
        line_buf_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce0,
        line_buf_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we0,
        line_buf_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d0,
        line_buf_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address1,
        line_buf_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce1,
        line_buf_we1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we1,
        line_buf_d1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d1);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_ready,
        window_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_address0,
        window_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_ce0,
        window_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_we0,
        window_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_d0);

    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352 : component conv2d_stream_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start,
        ap_done => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done,
        ap_idle => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_idle,
        ap_ready => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_ready,
        window_load_8 => window_load_8_reg_788,
        window_load_6 => window_load_6_reg_763,
        window_load_5 => window_load_5_reg_758,
        window_load_3 => window_load_3_reg_728,
        window_load_2 => window_load_2_reg_703,
        window_load => window_load_reg_673,
        window_load_7 => window_load_7_reg_783,
        window_load_4 => window_load_4_reg_733,
        window_load_1 => window_load_1_reg_698,
        rows => rows_read_reg_517,
        padded_cols => padded_cols_reg_633,
        bound4 => bound4_reg_768,
        local_kernel_load => local_kernel_load_reg_658,
        local_kernel_load_1 => local_kernel_load_1_reg_678,
        local_kernel_load_2 => local_kernel_load_2_reg_683,
        local_kernel_load_3 => local_kernel_load_3_reg_708,
        local_kernel_load_4 => local_kernel_load_4_reg_713,
        local_kernel_load_5 => local_kernel_load_5_reg_738,
        local_kernel_load_6 => local_kernel_load_6_reg_743,
        local_kernel_load_7 => local_kernel_load_7_reg_773,
        local_kernel_load_8 => local_kernel_load_8_reg_778,
        cols => cols_read_reg_510,
        line_buf_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address0,
        line_buf_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce0,
        line_buf_we0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we0,
        line_buf_d0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d0,
        line_buf_q0 => line_buf_q0,
        line_buf_address1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address1,
        line_buf_ce1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce1,
        line_buf_we1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we1,
        line_buf_d1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d1,
        line_buf_q1 => line_buf_q1,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        sub105 => sub105_reg_644,
        out_stream_TDATA => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDATA,
        out_stream_TVALID => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        out_stream_TREADY => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TREADY,
        out_stream_TKEEP => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TKEEP,
        out_stream_TSTRB => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TSTRB,
        out_stream_TUSER => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TUSER,
        out_stream_TLAST => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TLAST,
        out_stream_TID => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TID,
        out_stream_TDEST => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDEST,
        p_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out,
        p_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out_ap_vld,
        p_out1 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1,
        p_out1_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1_ap_vld,
        p_out2 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2,
        p_out2_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2_ap_vld,
        p_out3 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3,
        p_out3_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3_ap_vld,
        p_out4 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4,
        p_out4_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4_ap_vld,
        p_out5 => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5,
        p_out5_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5_ap_vld,
        p_phi_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out,
        p_phi_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out_ap_vld,
        p_phi9_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out,
        p_phi9_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out_ap_vld,
        p_phi10_out => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out,
        p_phi10_out_ap_vld => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out_ap_vld);

    CTRL_s_axi_U : component conv2d_stream_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        rows => rows,
        cols => cols,
        kernel_address0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_address0,
        kernel_ce0 => grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_kernel_ce0,
        kernel_q0 => kernel_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        ap_local_deadlock => ap_local_deadlock);

    mul_32s_32s_32_1_1_U58 : component conv2d_stream_mul_32s_32s_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        din0 => cols_read_reg_510,
        din1 => rows_read_reg_517,
        dout => mul104_fu_440_p2);

    mul_31ns_32ns_63_1_1_U59 : component conv2d_stream_mul_31ns_32ns_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 31,
        din1_WIDTH => 32,
        dout_WIDTH => 63)
    port map (
        din0 => bound4_fu_468_p0,
        din1 => bound4_fu_468_p1,
        dout => bound4_fu_468_p2);

    regslice_both_in_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDATA,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TKEEP,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TSTRB,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TUSER,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TLAST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TID,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component conv2d_stream_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TDEST,
        vld_in => grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln30_fu_421_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln30_fu_421_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln30_fu_421_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_ready = ap_const_logic_1)) then 
                    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                bound4_reg_768 <= bound4_fu_468_p2;
                local_kernel_load_5_reg_738 <= local_kernel_q0;
                local_kernel_load_6_reg_743 <= local_kernel_q1;
                window_load_5_reg_758 <= window_q0;
                window_load_6_reg_763 <= window_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                cols_read_reg_510 <= cols;
                icmp_ln30_reg_629 <= icmp_ln30_fu_421_p2;
                rows_read_reg_517 <= rows;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                icmp_ln52_reg_649 <= icmp_ln52_fu_450_p2;
                padded_cols_reg_633 <= padded_cols_fu_427_p2;
                sub105_reg_644 <= sub105_fu_444_p2;
                trunc_ln50_reg_639 <= trunc_ln50_fu_432_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                local_kernel_load_1_reg_678 <= local_kernel_q1;
                local_kernel_load_2_reg_683 <= local_kernel_q0;
                window_load_1_reg_698 <= window_q1;
                window_load_2_reg_703 <= window_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                local_kernel_load_3_reg_708 <= local_kernel_q0;
                local_kernel_load_4_reg_713 <= local_kernel_q1;
                window_load_3_reg_728 <= window_q0;
                window_load_4_reg_733 <= window_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                local_kernel_load_7_reg_773 <= local_kernel_q0;
                local_kernel_load_8_reg_778 <= local_kernel_q1;
                window_load_7_reg_783 <= window_q0;
                window_load_8_reg_788 <= window_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                local_kernel_load_reg_658 <= local_kernel_q0;
                window_load_reg_673 <= window_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln30_fu_421_p2, ap_CS_fsm_state2, icmp_ln52_fu_450_p2, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done, ap_CS_fsm_state9, ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln30_fu_421_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((icmp_ln30_fu_421_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln52_fu_450_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state14;
                elsif (((icmp_ln52_fu_450_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state9) and (grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state14) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln52_1_fu_456_p2 <= std_logic_vector(unsigned(trunc_ln50_reg_639) + unsigned(ap_const_lv31_2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done)
    begin
        if ((grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_done, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_done, grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_done = ap_const_logic_0) or (grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_done = ap_const_logic_0) or (grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_lv1_0;

    ap_ready_assign_proc : process(ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bound4_fu_468_p0 <= bound4_fu_468_p00(31 - 1 downto 0);
    bound4_fu_468_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_1_fu_456_p2),63));
    bound4_fu_468_p1 <= bound4_fu_468_p10(32 - 1 downto 0);
    bound4_fu_468_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(padded_cols_reg_633),63));
    grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_ap_start_reg;
    grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state9);
    icmp_ln30_fu_421_p0 <= cols;
    icmp_ln30_fu_421_p2 <= "1" when (signed(icmp_ln30_fu_421_p0) > signed(ap_const_lv32_80)) else "0";
    icmp_ln52_fu_450_p2 <= "1" when (signed(padded_rows_fu_435_p2) > signed(ap_const_lv32_0)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_in_stream_TREADY, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            in_stream_TREADY_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_address0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address0, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address0;
        else 
            line_buf_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    line_buf_address1_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address1, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_address1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_address1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_address1;
        else 
            line_buf_address1 <= "XXXXXXXXX";
        end if; 
    end process;


    line_buf_ce0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce0, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce0;
        else 
            line_buf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_ce1_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce1, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_ce1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_ce1;
        else 
            line_buf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d0;
        else 
            line_buf_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_d1_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d1, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_d1;
        else 
            line_buf_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    line_buf_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we0, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we0, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we0;
        else 
            line_buf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    line_buf_we1_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we1, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we1, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            line_buf_we1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_line_buf_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            line_buf_we1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_42_2_fu_340_line_buf_we1;
        else 
            line_buf_we1 <= ap_const_logic_0;
        end if; 
    end process;


    local_kernel_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_address0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            local_kernel_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_kernel_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            local_kernel_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_kernel_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            local_kernel_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            local_kernel_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_address0;
        else 
            local_kernel_address0 <= "XXXX";
        end if; 
    end process;


    local_kernel_address1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            local_kernel_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            local_kernel_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            local_kernel_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            local_kernel_address1 <= ap_const_lv64_1(4 - 1 downto 0);
        else 
            local_kernel_address1 <= "XXXX";
        end if; 
    end process;


    local_kernel_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_ce0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            local_kernel_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            local_kernel_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_ce0;
        else 
            local_kernel_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    local_kernel_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            local_kernel_ce1 <= ap_const_logic_1;
        else 
            local_kernel_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    local_kernel_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_we0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            local_kernel_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_33_1_fu_332_local_kernel_we0;
        else 
            local_kernel_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_out_stream_TVALID;
    padded_cols_fu_427_p2 <= std_logic_vector(unsigned(cols_read_reg_510) + unsigned(ap_const_lv32_2));
    padded_rows_fu_435_p2 <= std_logic_vector(unsigned(rows_read_reg_517) + unsigned(ap_const_lv32_2));
    sub105_fu_444_p2 <= std_logic_vector(unsigned(mul104_fu_440_p2) + unsigned(ap_const_lv32_FFFFFFFF));
    trunc_ln50_fu_432_p1 <= rows_read_reg_517(31 - 1 downto 0);

    window_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_address0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_address0 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_address0 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            window_address0 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            window_address0 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            window_address0 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            window_address0 <= ap_const_lv64_2(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            window_address0 <= ap_const_lv64_1(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_address0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_address0;
        else 
            window_address0 <= "XXXX";
        end if; 
    end process;


    window_address1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_address1 <= ap_const_lv64_6(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_address1 <= ap_const_lv64_5(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_address1 <= ap_const_lv64_4(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            window_address1 <= ap_const_lv64_8(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            window_address1 <= ap_const_lv64_7(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            window_address1 <= ap_const_lv64_3(4 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            window_address1 <= ap_const_lv64_0(4 - 1 downto 0);
        else 
            window_address1 <= "XXXX";
        end if; 
    end process;


    window_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_ce0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            window_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_ce0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_ce0;
        else 
            window_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    window_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_const_logic_1 = ap_CS_fsm_state14) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0)))) then 
            window_ce1 <= ap_const_logic_1;
        else 
            window_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    window_d0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_d0, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi9_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out5;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_d0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_d0;
        else 
            window_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    window_d1_assign_proc : process(grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out, grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            window_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            window_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi_out;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            window_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out2;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            window_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_out3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            window_d1 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_52_5_VITIS_LOOP_53_6_fu_352_p_phi10_out;
        else 
            window_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    window_we0_assign_proc : process(ap_CS_fsm_state2, grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_we0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            window_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            window_we0 <= grp_conv2d_stream_Pipeline_VITIS_LOOP_46_3_VITIS_LOOP_47_4_fu_346_window_we0;
        else 
            window_we0 <= ap_const_logic_0;
        end if; 
    end process;


    window_we1_assign_proc : process(icmp_ln30_reg_629, icmp_ln52_reg_649, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state11, ap_CS_fsm_state14, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state10) or ((icmp_ln30_reg_629 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state14) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (icmp_ln52_reg_649 = ap_const_lv1_1)))) then 
            window_we1 <= ap_const_logic_1;
        else 
            window_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
